ga4gh/ga4gh-server

- ga4gh/server/__init__.py
- ga4gh/server/views.py
- setup.py
I've replaced the werkzeug calls with Flask calls, and added two flask extensions that make this easier. Tests pass.
> Flaskify 2

- .travis.yml
- ga4gh/server/__init__.py
- tests/__init__.py
- tests/test_views.py
This includes a few PEP8 issues that had accumulated in the code base as well
as automatic PEP8 testing for travis.
> Improve PEP8 compliance.

- ga4gh/protocol.py
- tests/test_views.py
This causes the following error if a field is not set in the request:
File "/usr/local/google/home/melanielc/git/server/ga4gh/server/views.py", line 21, in handleHTTPPost
protocolRequest = protocolClass.fromJSON(data)
File "/usr/local/google/home/melanielc/git/server/ga4gh/protocol.py", line 126, in fromJSON
return cls._decode(d)
File "/usr/local/google/home/melanielc/git/server/ga4gh/protocol.py", line 153, in _decode
instance.__dict__[k] = v
UnboundLocalError: local variable 'v' referenced before assignment
> Fill in test cases for Views unit test

- .travis.yml
Googled around and found this hack:
https://github.com/travis-ci/travis-ci/issues/1748#issuecomment-32170079
The fix works; see this travis build:
https://travis-ci.org/dcolligan/server/builds/47190231
> Fix travis security issue

- .travis.yml
This will generate a coverage report when running tests.
> Add test coverage to travis run

- setup.py
Some tiny PEP8 fixes for setup.py. I'm not particularly worried about setup.py following PEP8 in general, but this will stop my editor from complaining!
> PEP 8 fixes

- tests/test_views.py
Verify that CORS is setting headers correctly.
> Add unit test for CORS functionality.

- ga4gh/cli.py
- ga4gh/client.py
- tests/test_schemas.py
> Rename single-character variables

- .gitignore
- ga4gh/_protocol_definitions.py
- scripts/generate_schemas.py
A first attempt at addressing #67
Feedback appreciated.
> Dcolligan 67

- STYLE.md
This is a starting point for a style guide. It is intentionally sparse for now. Let's first make sure that we are OK with this format and the principles outlined here. Any additions should be added in a separate PR afterwards.
> Style guide

- .gitignore
- ga4gh/cli.py
- ga4gh/client.py
- tests/test_client.py
Issue #76 -- obviously very WIP.  Going to be adding client endpoints to this branch as I go along...
Tried to follow the conventions established in the code already.  @jeromekelleher
> Added referencesets/search client endpoint

- .travis.yml
- scripts/run_tests.py
> Add run_tests.py to imitate travis run

- ga4gh/cli.py
- ga4gh/frontend.py
This works, but I'm still not sure what preference we want to override what; see discussion in #70
> Dcolligan 70 cfg file

- server_benchmark.py
Here's a more substantive strawman for #46.
Open issues:
* How many queries?
* Which queries?
> ga4gh_benchmark server benchmarking

- ga4gh/datamodel/variants.py
- tests/test_backends.py
> Improved genotype handling in wormtable variant sets

- ga4gh/frontend.py
- ga4gh/frontend_exceptions.py
- tests/test_exceptions.py
> Server now catches and handles exceptions

- README.txt
- STYLE.md
- ga4gh/cli.py
- ga4gh/client.py
- scripts/google_examples.py
- tests/test_backends.py
- tests/test_cli.py
- tests/test_client.py
- tests/test_schemas.py
Implemented client search endpoints for:
- references
- readGroupSets
- callSets
- reads
Did a bunch of refactoring as well.
Does not close #76
> Implement remaining client search endpoints

- tests/test_end_to_end.py
This sets up some basic cases for interactions between the backend and the server. It will definitely need more filling in, but this gives us a basic framework to build off of.
> Add an end to end test for the server.

- STYLE.md
Added guidelines on how to use imports.
> Refined the style imports section.

- ga4gh/cli.py
> change variantSetIds argparse option to avoid clashing with verbosity

- ga4gh/cli.py
- scripts/google_examples.py
> Adds optional extended outputFormat

- .gitignore
- ga4gh/client.py
> verbose client display

- ga4gh/protocol.py
- tests/test_schemas.py
Flake8 added some new errors, here's quick fixes. All travis builds will fail for now, so let's merge this quickly.
> Fix new flake8 errors

- STYLE.md
Added some notes on docstring comments and on the structure of test cases.
> Docstring conventions and some testing style.

- server_benchmark.py
Use cProfile to report top 25% of CPU-time-consuming python
functions.
Addresses https://github.com/ga4gh/server/issues/46
---
Just the diagnostic code without any of the ideas I explored in https://github.com/ga4gh/server/issues/46.
Snippet at the end suggests we might add Backend.reportProfile(), but since this is isolated to a development script rather than deployed production code I don't think that's necessary until we have a second profiler that would use it, and I don't know what other profilers we might add.
> Add CPU profiling to server_benchmark

- .gitignore
- .travis.yml
- ga4gh/cli.py
- ga4gh/client.py
- scripts/auth.yml.example
- scripts/google_examples.py
- tests/test_cli.py
- tests/test_client.py
The remaining client endpoints.
There were a lot more design decisions to be made here vs the last client endpoint PR.  Feedback appreciated.
Will close #76
> 76 client endpoints 2

- ga4gh/cli.py
Refactor in preparation for reuse of a lot of the client cli functionality by the conversion tools
Does not close #83
> Refactor cli client methods

- scripts/process_schemas.py
- tests/test_schemas.py
Minimal changes to fix flake8 issues.
This should be uncontroversial, so lets try to merge it ASAP and we can then rebase any existing PRs.
> Fixed issues with new flake version.

- ga4gh/frontend.py
> refactoring frontend endpoints

- ga4gh/cli.py
A refactor in preparation for there being multiple code paths that use command line arguments to instantiate GAWhateverRequests.
Does not close #83
> Create requestFactory and refactor cli to use it

- ga4gh/client.py
- tests/unit/test_client.py
Produces these log messages:
_debugLevel 0:
nothing
_debugLevel 1:
```
ga4gh.client: POST https://www.googleapis.com/genomics/v1beta2/variants/search
```
_debugLevel 2:
```
ga4gh.client: POST https://www.googleapis.com/genomics/v1beta2/variants/search
[dump of Json response]
```
Issue #130
> Added logger to client

- README.txt
- ga4gh/frontend.py
- ga4gh/frontend_exceptions.py
- tests/unit/test_end_to_end.py
- tests/unit/test_views.py
- tests/utils.py
> Add version info to URLs

- README.txt
- ga4gh/cli.py
- tests/unit/test_cli.py
> no arg variants-search call returns all variants

- ga2sam_dev.py
- ga2vcf_dev.py
- ga4gh/cli.py
- ga4gh/converters.py
- setup.py
> Add infrastructure for ga2vcf and ga2sam tools

- tests/unit/test_backends.py
- tests/unit/test_schemas.py
This fixes an issue in which `tests/test_backends.py` ERRORed when run in isolation using
```
nosetests -vs tests/test_backends.py
```
> Fixes import issue for tests utils.

- setup.py
Fixes missing install requirement.
> Added install requires for humanize package.

- ga4gh/backend.py
- ga4gh/datamodel/variants.py
- ga4gh/frontend.py
- tests/unit/test_backends.py
- tests/unit/test_end_to_end.py
- tests/unit/test_views.py
> added callSet Search backend and unit tests

- README.txt
The README was updated as follows:
*A new "installing the server" section was added near the top, specifying the steps for a successful first-time install, with examples.
*The documentation was updated to reflect running pip with the requirements.txt file
* the test section (running nosetests) originally located at the bottom of the file was moved up into the main install section, so that first-time users can easily verify their install.
> Updated README file with install instructions for first-time users.

- ga4gh/backend.py
- ga4gh/datamodel/variants.py
The TabixVariantSet is currently broken (not surprisingly since we have no test coverage...). This PR is the minimum required to make it operational.
> Minimum patching up to make tabix backend work.

- ga4gh/frontend_exceptions.py
- tests/unit/test_exceptions.py
solving issue #176 , map NotImplementedError to frontend exceptions to communicate the error to client.
> map NotImpmentedError to frontend

- scripts/process_schemas.py
To allow for development of experimental server code using ga4gh schemas still in development (not tagged with an official version number), I modified the process_schemas.py script to allow generating the _protocol_definitions.py file from a local directory (for example, a local clone of a development fork of ga4gh/schemas). 
The script runs as before when not provided with an optional --output-file (-o) argument.
> modify process_schemas script to work on locally stored Avro schemas.

- ga4gh/backend.py
- ga4gh/backend_exceptions.py
- ga4gh/cli.py
- ga4gh/frontend.py
- ga4gh/frontend_exceptions.py
- ga4gh/serverconfig.py
- tests/unit/test_views.py
> Add server request/response validation

- README.txt
- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/datamodel/variants.py
- tests/unit/test_backends.py
- tests/unit/test_end_to_end.py
> Infer variant type instead of passing it via cli

- requirements.txt
- tests/unit/test_imports.py
- tests/utils.py
Not sure if this is more trouble than it's worth at a project of our size, but...
And not even sure that this is the best way to do this, even if we do want it...
This is a test that ensures that no circular imports are present in the project.
Feedback welcome.
> Module import tests (cycles, layering)

- ga4gh/cli.py
- tests/end_to_end/test_gestalt.py
- tests/end_to_end/test_server.py
- tests/unit/test_util_decorators.py
- tests/utils.py
change default sink values from empty strings to none
add end to end test
adds test annotations
> End to end test

- ga4gh/cli.py
- tests/datadriven/__init__.py
- tests/datadriven/test_asserts.py
> Add assert methods to data driven test suite

- .travis.yml
- ga4gh/cli.py
- tests/unit/test_simulator.py
Increase required test coverage to 85%
Issue #222
Issue #195
> Add tests for simulated variant sets

- ga4gh/cli.py
- tests/end_to_end/server.py
- tests/end_to_end/test_gestalt.py
We should test some kind of return values from the server before this is committed (as per the issue).
Issue #226
> Make test_gestalt use SimulatedBackend

- scripts/google_examples.py
- scripts/process_schemas.py
- scripts/run_tests.py
- scripts/utils.py
This is a script to easily upload a version of the server to pypi
Also do some refactoring
> Add scripts/upload_source.py

- ga4gh/datamodel/variants.py
> Remove Tabix

- ga4gh/backend.py
- ga4gh/datamodel/variants.py
- ga4gh/exceptions.py
- ga4gh/frontend.py
- ga4gh/templates/index.html
- tests/unit/test_views.py
Updates the info page with some extra information. Closes #245 
Also adds some tests for the info page, and fixed some tests that were excluded in test_views.
One issue we have here is that I can't find a way to determine the number of variants in a VariantFile; @bioinformed, is there a straightforward way to do this?
> Added information on configuration and variants.

- ga4gh/frontend.py
- ga4gh/serverconfig.py
- tests/unit/test_simulated_stack.py
- tests/unit/test_views.py
- Adds an extraConfig dictionary to `configure` to allow us to easily
configure the tests.
- Refactored test_views to get rid of malformed requests, and set up
full request validation.
- Renamed test_end_to_end to test_simulated_stack and removed the
wormtable dependency there.
Fixes issues #250 and #188.
> Improved testing for simulated backends.

- server_benchmark.py
Also added some CLI parameters to allow us to easily compare different
variant set implementations.
> Updated benchmark to use new code layout.

- convert_error_code.py
- ga4gh/backend.py
- ga4gh/exceptions.py
- ga4gh/frontend.py
- ga4gh/serverconfig.py
- tests/unit/test_protocol_errors.py
- Adds a simple script to decode error codes.
- Adds tests for bad page sizes, and adds a configuration key for
default page size.
- Improves request validation error messages
> Initial outline of protocol error testing.

- ga4gh/avrotools.py
- ga4gh/protocol.py
- tests/unit/test_avrotools.py
- tests/unit/test_imports.py
Intended uses of this tool: I was thinking that if the server is in DEBUG mode we could add information from ValidationTool to the request / response validation error info.
In any event, this is worth including in some form, since figuring out what is failing validation is very useful.
> Added avrotools and tests

- ga4gh/datamodel/variants.py
- tests/datadriven/test_variants.py
reworked on #221, this should be a cleaner version now. ready for revising
> resolving issue #221

- tests/datadriven/__init__.py
- tests/datadriven/test_asserts.py
- tests/datadriven/test_variants.py
> adds assertAlmostEqual and assertNotAlmostEqual

- ga4gh/exceptions.py
- tests/unit/test_exceptions.py
> Prevent leaking internal error messages to clients

- tests/datadriven/test_variants.py
Resolving issue #269 systematic checks for extracted gaVariants within an interval. test against pyvcfVariants
> resolving issue #269

- ga4gh/datamodel/variants.py
- tests/datadriven/test_variants.py
GACall field phaseset unset #265
> resolving issue #265

- ga4gh/cli.py
- requirements.txt
- server_benchmark.py
- setup.py
(except for README and relevant comments)
> Remove all references to wormtable

- ga4gh/cli.py
- ga4gh/datamodel/variants.py
- tests/datadriven/test_variants.py
Reinstate full v0.5.1 semantics for variants-search.
> Reverted to v0.5 semantics for variants-search.

- ga4gh/backend.py
- ga4gh/datamodel/reads.py
- ga4gh/exceptions.py
- ga4gh/frontend.py
- tests/datadriven/test_reads.py
- tests/datadriven/test_variants.py
- tests/end_to_end/server.py
- tests/end_to_end/test_gestalt.py
- tests/unit/test_simulator.py
- tests/unit/test_views.py
This PR is branched off of the getReadAlignments implementation.
Tests are failing because of some validation stuff... is there any way for avro to tell us what field is invalid and why?
Issue #246
> 246 reads search

- .travis.yml
- README.txt
- ga4gh/cli.py
Also minor changes to change wormtable related values elsewhere.
> Removed wormtable references from README

- ga4gh/datamodel/variants.py
Pysam and htslib provide the functionality to access files remotely over FTP/HTTP. We simply need to provide a URL as an argument, and the network accesses happen transparently. This seems like useful functionality, and might allow us to deploy easily on (e.g.) Amazon using S3 storage. This PR is a rough POC implementation to illustrate how we might do this.
Questions:
1. Is this something we want to support?
2. Will this be sufficient to access data stored in Amazon S3 (http://aws.amazon.com/public-data-sets/) like 1000G?
Issues:
1. How do we manage input data? (In this POC, I've just dumped a JSON file with the URLS into the variants dir. We should think hard about what the right way to do this is.)
2. How do we manage the index files? Currently, htslib downloads the index file and …
> POC implementation of accessing remote data.

- ga4gh/datamodel/variants.py
- ga4gh/exceptions.py
- tests/datadriven/test_variants.py
also raise exception when callsetid can not be found in the vcf files
> resolving issue #299, Call data not being returned for variants/search

- ga4gh/client.py
- tests/unit/test_client.py
Minor improvements to client logging, and brings the client module up to date to use recent improvements in the SearchRequest API.
> Improved client logging.

- ga4gh/datamodel/__init__.py
- ga4gh/datamodel/reads.py
- ga4gh/datamodel/variants.py
- ga4gh/exceptions.py
- tests/unit/test_sanitizer.py
> validation POC

- .travis.yml
(Lol @ GitHub's broken merge model)
> Fix master by excluding conf.py from flake8 check

- .travis.yml
- ga4gh/datamodel/reads.py
- scripts/run_tests.py
> Fixes redundant and slow flake8 run

- ga4gh/__init__.py
Ready for tagging so we can review the docs and test the pypi package.
> Version bump.

- README.txt
- docs/source/Makefile
- docs/source/configuration.rst
- docs/source/demo.rst
- docs/source/development.rst
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/introduction.rst
- Updated Makefile to be more standard and add a default target
- Improved the configuration, installation and demo pages.
- Started a full rewrite of the development page.
> Update of the documentation.

- ga4gh/datamodel/variants.py
- ga4gh/exceptions.py
> Fix URL support for variants

- docs/source/development.rst
> Added docs describing branch strategy

- docs/source/development.rst
> Update docs to reflect master -> stable change

- ga4gh/backend.py
- tests/unit/test_backends.py
- tests/unit/test_response_generators.py
> Refactor and test readGenerator

- tests/unit/test_imports.py
- tests/unit/test_protocol_errors.py
- tests/unit/test_simulated_stack.py
- tests/unit/test_views.py
Instead use module and class level unittest setup
Issue #364
> Get rid of global keyword in tests

- scripts/process_schemas.py
- fix some text wrapping bugs
- refactor code so we're not computing whitespace everywhere
- make the version argument be literally accepted when the -i flag is used
> Make process_schemas.py easier to read / use

- .gitignore
- ga4gh/avrotools.py
- ga4gh/datamodel/__init__.py
- ga4gh/datamodel/reads.py
- ga4gh/datamodel/variants.py
- ga4gh/exceptions.py
- requirements.txt
- tests/end_to_end/client.py
- tests/end_to_end/remoteTestData/reads/remoteTest/urls.json
- tests/end_to_end/remoteTestData/references/placeholder.txt
- tests/end_to_end/remoteTestData/variants/placeholder.txt
- tests/end_to_end/server.py
- tests/end_to_end/server_test.py
- tests/end_to_end/test_gestalt.py
- tests/end_to_end/test_remote_fetch.py
- tests/utils.py
> Test remote reads functionality

- docs/source/development.rst
> Added directions about process_schemas.py to docs

- ga4gh/frontend.py
- tests/unit/test_views.py
> Add 'current' url version alias

- tests/unit/test_backends.py
> Test backend._topLevelObjectGenerator

- ga4gh/backend.py
- ga4gh/datamodel/graphs.py
- ga4gh/frontend.py
- tests/data/graphs/graphData_v023.sql
- tests/datadriven/test_references.py
Significant refactor now has all graph-based logic separated out into a new GraphBackend class, which implements a graph-specific runSearchRequest (uses database).
> Refactored GraphBackend

- ga4gh/exceptions.py
The develop branch is currently broken after a recent merge. This PR fixes it.
> Fixed schemaTool problems.

- ga4gh/avrotools.py
- ga4gh/exceptions.py
- tests/datadriven/__init__.py
- tests/unit/test_avrotools.py
- tests/unit/test_protocol_errors.py
- tests/unit/test_schemas.py
Also do a lot of refactoring
Issue #404
> Eliminate avrotools generator patterns

- ga4gh/_protocol_definitions.py
- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/client.py
- ga4gh/datamodel/graphs.py
- ga4gh/frontend.py
- ga4gh/sidegraph.py
- tests/datadriven/test_reads.py
- tests/unit/test_sidegraph.py
- tests/unit/test_views.py
`subgraph/extract` endpoint added, other graph endpoint code cleaned up, middle-layer code refactored, appropriate unit tests added.
> Subgraph/extract endpoint, etc

- .gitignore
- ga4gh/__init__.py
- ga4gh/backend.py
- ga4gh/frontend.py
- tests/unit/test_backends.py
- tests/unit/test_response_generators.py
- Bump to version ~~0.1.0~~ 0.1.1
- Refactor and test backend generators
- Take out unused paths
- added sphinx exception to gitignore
#391
> Bugfix release

- configtest_dev.py
- ga4gh/cli.py
- ga4gh/configtest.py
- setup.py
- tests/unit/test_imports.py
Framework for the server validator work. see #417.
> Framework for server config validator

- ga4gh/backend.py
- requirements.txt
- setup.py
Specifies versions of setuptools, requests libraries for older servers, plus fixes page token bug.
> Misc fixes to bugs found by Adam.

- docs/source/index.rst
- docs/source/status.rst
> Update docs with 'Implementation Status' section

- ga4gh/frontend.py
> Added more config vars to html page

- tests/data/graphs/graphData_v023.sql
GraphJoin-referenceSet dataset values in graphData_v023.sql were flipped.
> Resolved Issue #427

- ga4gh/exceptions.py
- tests/unit/test_exceptions.py
> Ensure exception codes in range [0, 2**31-1]

- docs/source/demo.rst
> Add note about fedora install

- .travis.yml
- docs/source/demo.rst
Revert non-released changed to stable branch
part of issue #478
> Stable revert

- ga4gh/datamodel/__init__.py
- ga4gh/datamodel/reads.py
- ga4gh/datamodel/references.py
- ga4gh/datamodel/variants.py
- ga4gh/frontend.py
- ga4gh/serverconfig.py
- tests/unit/test_file_handle_cache.py
This is the implementation for the open file handles cache (issue #441)
Please review and let me know if you see any problems with the proposed implementation.
The size of the cache (maximum number of open files) can be set in serverconfig.py with the variable CACHE_MAX_SIZE currently set to 50.
Thanks!
Esther
> Cache for open file handles

- ga4gh/datamodel/reads.py
- ga4gh/exceptions.py
- tests/datadriven/test_reads.py
> Improve error on read query with invalid refName

- .travis.yml
See http://docs.travis-ci.com/user/migrating-from-legacy/
> Enable builds on new Travis infrastructure

- ga4gh/frontend.py
- ga4gh/serverconfig.py
- tests/unit/test_oidc.py
- tests/unit/test_protocol_errors.py
- tests/unit/test_simulated_stack.py
- tests/unit/test_views.py
> Get rid of reload(fronend) calls in tests

- ga4gh/_protocol_definitions.py
- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/datamodel/reads.py
- ga4gh/exceptions.py
- tests/end_to_end/test_gestalt.py
- tests/end_to_end/test_oidc.py
- tests/end_to_end/test_remote_fetch.py
- tests/unit/test_avrotools.py
- tests/unit/test_backends.py
- tests/unit/test_cli.py
- tests/unit/test_exceptions.py
- tests/unit/test_response_generators.py
- tests/unit/test_schemas.py
- tests/unit/test_simulated_stack.py
- tests/unit/test_views.py
Bring server up to date with linear schemas
(submitting now to get the CI)
Issue #369
> Bring server up to date with linear schemas

- ga4gh/cli.py
- tests/end_to_end/client.py
- tests/end_to_end/server.py
- tests/end_to_end/test_oidc.py
Issue #503 
Now looks normal:
```
$ nosetests -s -v tests/end_to_end/test_oidc.py
testMultipleOidcClients (tests.end_to_end.test_oidc.TestOidc) ... ok
testOidc (tests.end_to_end.test_oidc.TestOidc) ... ok
testOidcBadLoginKey (tests.end_to_end.test_oidc.TestOidc) ... ok
testOidcBadLoginPassword (tests.end_to_end.test_oidc.TestOidc) ... ok
----------------------------------------------------------------------
Ran 4 tests in 20.339s
OK
```
> Remove test_oidc spam

- setup.py
Issue #498
Hopefully this approach will be more robust than requiring a specific version of setuptools.
> Removed mandatory ez_setup usage.

- ga4gh/_protocol_definitions.py
- scripts/process_schemas.py
- tests/unit/test_schemas.py
> added kwargs field to protocol __init__ methods

- ga4gh/frontend.py
- tests/unit/test_views.py
> Delete unused routes

- ga4gh/datamodel/graphs.py
as returned via the references/search endpoint.
> fixed missing fields in References

- tests/unit/test_intervals.py
Issue #465. This reduces the time from 18s to 0.2 seconds on my machine.
Thanks for nagging on this one @dcolligan!
> Removed overly-large test case.

- ga4gh/cli.py
- ga4gh/client.py
- ga4gh/exceptions.py
- tests/unit/test_exceptions.py
> Create client exception hierarchy

- ga4gh/backend.py
- ga4gh/datamodel/__init__.py
- ga4gh/datamodel/datasets.py
- ga4gh/datamodel/reads.py
- ga4gh/datamodel/references.py
- ga4gh/datamodel/variants.py
- ga4gh/exceptions.py
- tests/datadriven/__init__.py
- tests/datadriven/test_reads.py
- tests/datadriven/test_references.py
- tests/datadriven/test_variants.py
- tests/end_to_end/test_gestalt.py
- tests/unit/test_backends.py
- tests/unit/test_faultydata.py
- tests/unit/test_response_generators.py
- tests/unit/test_simulated_stack.py
- tests/unit/test_simulator.py
- tests/unit/test_views.py
> Compound id refactor

- ga4gh/backend.py
- tests/unit/test_backends.py
- tests/unit/test_compound_ids.py
Also adding test_compound_ids.py because it weirdly did not
get committed in the compoundId refactor
> Add _safeMapQuery to backend

- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/client.py
- ga4gh/frontend.py
- tests/unit/test_cli.py
- tests/unit/test_client.py
- tests/unit/test_views.py
First pass.  Still need to add tests.  Feedback welcome.
```
$ python client_dev.py -O callsets-get dataset1:1kg-phase1:HG00533 http://localhost:8000/current
dataset1:1kg-phase1:HG00533
```
Issue #527
> Implement GET /callsets/{id}

- ga4gh/datamodel/graphs.py
- ga4gh/serverconfig.py
- ga4gh/sidegraph.py
1. SQL bug causing unnecessary iteration on large paging requests
2. FASTA index not properly caching causing serious latency in pulling multiple sequences at once.
> Fixed two serious performance issues in graph server

- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/client.py
- ga4gh/datamodel/__init__.py
- ga4gh/datamodel/variants.py
- ga4gh/frontend.py
- tests/datadriven/test_variants.py
- tests/unit/test_cli.py
- tests/unit/test_client.py
- tests/unit/test_compound_ids.py
- tests/unit/test_views.py
Half-finished; will apply comments in #530 later
Issue #528
> Implement GET /variants/{id}

- tests/end_to_end/test_gestalt.py
- tests/end_to_end/test_oidc.py
- tests/unit/test_backends.py
- tests/unit/test_views.py
- tests/utils.py
> Consolidate hardcoded test values

- tests/unit/test_simulated_stack.py
> Added tests for GET callset.

- ga4gh/datamodel/variants.py
- tests/datadriven/test_variants.py
> Change getVariant behavior to conform to 0.6

- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/datamodel/__init__.py
- ga4gh/datamodel/reads.py
- ga4gh/datamodel/references.py
- ga4gh/exceptions.py
- tests/datadriven/test_references.py
- tests/unit/test_sanitizer.py
- tests/unit/test_simulated_stack.py
- Added general range checking for ListReferenceBases, and raise a HTTP
416 when these are out of bounds.
- Updated the object models for ReferenceSet and References, and
generally refactored reference.py.
- Updated the simulated object models, and tested the translation of
these through the protocol.
- Added more tests for ListReferenceBases.
> Tidy-up reference handling.

- .gitignore
- scripts/download_data.py
- scripts/process_schemas.py
- scripts/update_data.py
- scripts/utils.py
Still a WIP; not very well factored right now
This current code will download the index files for, write, compress, and index all the VCFs from a given site (only NCBI supported right now) in about 3 minutes.  Unfortunately, it takes a few tries since htslib segfaults a lot...
Question for @jeromekelleher ... which (read) samples do we want to download?  There's quite a lot of them and I expect we want to download a subset...
Issue #312
> Script to download data from NCBI, etc.

- scripts/download_data.py
- scripts/utils.py
> Add references support to download data script

- scripts/download_data.py
Only the most recent commit has this PR's changes... the previous two are in other PRs.
Issue #582
> 582 change names

- ga4gh/datamodel/reads.py
- tests/datadriven/test_reads.py
- tests/utils.py
> Add programs field to read groups

- ga4gh/templates/index.html
> Add deobfuscated ids to html page

- ga4gh/cli.py
- tests/end_to_end/server.py
> Added configurable host string for server CLI.

- ga4gh/datamodel/reads.py
- tests/datadriven/test_reads.py
- tests/end_to_end/test_remote_fetch.py
> Search reads now takes reference ID

- ga4gh/datamodel/variants.py
- tests/datadriven/test_variants.py
> Fix get callsets bug

- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/client.py
- ga4gh/frontend.py
- tests/unit/test_cli.py
- tests/unit/test_client.py
- tests/unit/test_simulated_stack.py
- tests/unit/test_views.py
> Implement GET /datasets/{id}

- ga4gh/converters.py
Alas, I was so busy getting the Python syntax right that I didn't adequately check the actual tests here…
> Fix strand flag copy-pasto

- ga4gh/_protocol_definitions.py
> Update _protocol_definitions to schemas/4568e6f6

- ga4gh/templates/index.html
> Fix misaligned references html

- ga4gh/datamodel/reads.py
- tests/datadriven/test_reads.py
> Make sampleId read group header's SM tag

- ga4gh/datamodel/reads.py
- tests/datadriven/test_reads.py
> Fill out read group experiment field

- ga4gh/datamodel/__init__.py
- ga4gh/datamodel/reads.py
- tests/unit/test_sanitizer.py
> Remove sanitizeGetRName

- ga4gh/datamodel/__init__.py
- ga4gh/datamodel/reads.py
- tests/datadriven/test_reads.py
> Make experiment part of the object hierarchy

- tests/unit/test_backends.py
> Fixed failing test case.

- ga4gh/datamodel/datasets.py
- ga4gh/datamodel/variants.py
- tests/unit/test_simulated_stack.py
> Set VariantSet and Dataset names

- ga4gh/datamodel/references.py
- ga4gh/exceptions.py
- scripts/download_data.py
- tests/data/references/Default.json
- tests/data/references/NCBI37.json
- tests/data/references/example_1.json
- tests/data/references/example_2.json
- tests/datadriven/__init__.py
- tests/datadriven/test_references.py
- tests/faultydata/references/inconsistent_reference_name.json
- tests/faultydata/references/invalid_refset_meta.json
- tests/faultydata/references/missing_refset_meta.json
- tests/faultydata/references/two_references.json
- tests/unit/test_faultydata.py
> Set metadata for reference sets

- requirements.txt
- tests/end_to_end/server.py
- tests/end_to_end/server_test.py
> Remove Twistd, since we're not using it anymore

- docs/source/api.rst
- docs/source/conf.py
- docs/source/index.rst
- ga4gh/_protocol_definitions.py
- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/client.py
- ga4gh/datamodel/datasets.py
- scripts/process_schemas.py
- tests/end_to_end/client.py
- tests/unit/test_client.py
- tests/utils.py
This is an initial pass at the client API docs. There's a lot to be filled out, but this is the basic idea.
The build docs are available at http://ga4gh-server.readthedocs.org/en/client-api-docs/api.html
(This builds on #643).
Thoughts? @diekhans, this should be up your street --- what do you think?
> Client api docs

- tests/unit/test_schemas.py
This test pushes our coverage in _protocoldefinitions.py to 100%.
> Added test for embedded values in ProtocolElements.

- ga4gh/exceptions.py
- tests/unit/test_exceptions.py
> Fixed bug in getExceptionClass.

- ga4gh/sidegraph.py
Replaced subgraph algorithm with one that traces out a subgraph symmetrically in both directions whenever it traverses a join.
> New subgraph algorithm

- docs/configuration.rst
- docs/demo.rst
- docs/installation.rst
- docs/status.rst
Update the docs for the data input format. Assumes #672 is accepted.
Needs some rebasing once other PRs are merged.
> Remaining docs update

- docs/demo.rst
- docs/development.rst
- docs/installation.rst
Needed for building on Ubuntu machines.
> Added libffi dependency on Debian instructions.

- ga4gh/datamodel/__init__.py
> Need to check for long on 32bit machines.

- README.txt
This links to https://gitter.im/ga4gh/server which you can join even if you aren't in the ga4gh organization
Closes #724
> Add a Gitter badge

- ga4gh/cli.py
- tests/end_to_end/test_client_json.py
> Added support for finding all read groups when no read group specified

- ga4gh/datamodel/__init__.py
- ga4gh/datamodel/variants.py
- tests/datadriven/test_variants.py
- tests/unit/test_compound_ids.py
> VariantSet metadata not correctly filled

- tests/unit/test_backends.py
> Add integer parsing tests. Fixes #682

- ga4gh/backend.py
- ga4gh/exceptions.py
- tests/unit/test_backends.py
Added getDatasetByName
Implemented DatasetNameNotFoundException that getDatasetByName will throw if the name does not exist
Rebased AbstractBackend tests
> Added tests for backend methods, refactored and updated tests.

- ga4gh/converters.py
Added header information to ga2sam.
> Added header information to ga2sam

- docs/development.rst
> Add link to git book to docs

- .gitignore
- docs/development.rst
> 764 ci docs

- tests/end_to_end/test_client_json.py
- tests/unit/test_cli.py
> Tests for fasta, etc. cli output options

- scripts/download_data.py
This PR should close #768, #719, and #635.
When merged, we need to close #719 and #635 manually.
Please see comments regarding this commit in #768.
> 768 merge seqfetcher

- scripts/download_data.py
```
$ python scripts/download_data.py
...
Finished in 21 seconds (21.84 seconds)
$ python scripts/download_data.py
Checkpoint found for 1 ... skipping ...
chrom: 1, maxPos: 138395, minPos: 10176
Checkpoint found for 2 ... skipping ...
chrom: 2, maxPos: 32403, minPos: 10178
Checkpoint found for 3 ... skipping ...
chrom: 3, maxPos: 81617, minPos: 60068
Checkpoint found for HG00096 ... skipping ...
Checkpoint found for HG00533 ... skipping ...
Checkpoint found for HG00534 ... skipping ...
Checkpoint found for 1 ... skipping ...
Checkpoint found for 2 ... skipping ...
Checkpoint found for 3 ... skipping ...
Finished in a moment (0.02 seconds)
$
```
Issue #721
> Create checkpoints for download_data

- ga4gh/datamodel/reads.py
In pursuit of #717, this PR provides simulated reads with random seeds derived from the overall simulator seed and the number of the read. (Node that you can still, I think, page through reads forever.)
The reads also generate themselves fragment IDs, lengths, and the appropriate number of quality scores and sequence bases.
> Generate random read sequences and qualities.

- ga4gh/frontend.py
> Fixes urlparse bug in startup code.

- docs/status.rst
Also created release notes section in docs. Release notes for earlier versions taken from GitHub UI.
> Added release notes.

- ga4gh/__init__.py
> Bumped to version 0.2.0a1.

- ga4gh/datamodel/references.py
- ga4gh/datamodel/variants.py
- requirements.txt
- setup.py
> Upgrade to pysam 0.8.4

- ga4gh/__init__.py
No bugs have appeared since version 0.2.0a1, so let's update to 0.2.0 and push to pypi.
> Version bump to 0.2.0.

- docs/development.rst
> Branching docs

- ga4gh/cli.py
- tests/unit/test_cli.py
Minor refactor to make server_main match client_main and adds tests for proper cli argument parsing
> Refactor server_main to match client_main - Issue #685

- ga4gh/datamodel/datasets.py
- ga4gh/datamodel/variants.py
Minor cleanup on the variation annotation branch to implement some unresolved comments on the original PR thread.
Depends on #839
> Minor cleanup

- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/datamodel/datasets.py
- ga4gh/datamodel/reads.py
- ga4gh/datamodel/references.py
- ga4gh/datamodel/variants.py
- ga4gh/datarepo.py
- ga4gh/frontend.py
- server_benchmark.py
- tests/datadriven/test_reads.py
- tests/end_to_end/test_client_json.py
- tests/unit/test_backends.py
- tests/unit/test_client.py
- tests/unit/test_converters.py
- tests/unit/test_faultydata.py
- tests/unit/test_imports.py
- tests/unit/test_references.py
- tests/unit/test_response_generators.py
- tests/unit/test_simulated_stack.py
- tests/unit/test_variants.py
- tests/unit/test_views.py
> Data repository refactor

- ga4gh/frontend.py
Hopefully completes the data repo refactor, bug fix since backend no longer contains the filesystem repository.
> Bug fix: Point to the new location of data repo

- ga4gh/backend.py
- ga4gh/client.py
- ga4gh/frontend.py
- tests/unit/test_client.py
> Add endpoint for finding variant annotation sets by ID

- docs/development.rst
> Document long running branch workflow

- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/datamodel/datasets.py
- ga4gh/datamodel/reads.py
- ga4gh/datamodel/references.py
- ga4gh/datamodel/variants.py
- ga4gh/datarepo.py
- ga4gh/frontend.py
- server_benchmark.py
- tests/datadriven/test_reads.py
- tests/end_to_end/test_client_json.py
- tests/unit/test_backends.py
- tests/unit/test_cli.py
- tests/unit/test_client.py
- tests/unit/test_converters.py
- tests/unit/test_faultydata.py
- tests/unit/test_imports.py
- tests/unit/test_references.py
- tests/unit/test_response_generators.py
- tests/unit/test_simulated_stack.py
- tests/unit/test_variants.py
- tests/unit/test_views.py
This brings the G2P branch up to date with recent changes in master. This is a simple merge, and can be done with the following commands:
```
$ git fetch upstream
$ git checkout upstream/g2p
$ git checkout -b g2p-update
$ git merge upstream/master
$ git push origin/g2p-update
```
@bwalsh, since you've been nominated to be the G2P branch manager (we had to pick someone, and you seemed the logical choice!), can you merge this PR once it passes CI? As the branch manager you should keep the g2p branch reasonably up-to-date with changes in master using merge PRs like this (see PR #862 for the documentation for this process).  I thought I'd create this merge PR, as an important refactor has happened in master recently which will cause conflicts down the line if we don't deal with it now.
> Topic branch update: G2P

- ga4gh/datamodel/reads.py
- ga4gh/datarepo.py
- ga4gh/frontend.py
- tests/end_to_end/test_client_json.py
- tests/unit/test_converters.py
> Refactor some server init

- ga4gh/_protocol_definitions.py
- ga4gh/backend.py
- ga4gh/datamodel/__init__.py
- ga4gh/datamodel/datasets.py
- ga4gh/datamodel/variants.py
- ga4gh/datarepo.py
- tests/unit/test_simulated_stack.py
- tests/unit/test_simulator.py
Makes the variant annotation set records return conform better to the schema closing #832 and #833 
WIP: Depends on #869
> Variant annotation set names and analysis field

- ga4gh/cli.py
- ga4gh/datamodel/datasets.py
- ga4gh/datarepo.py
- ga4gh/exceptions.py
- ga4gh/repo_manager.py
- repo_dev.py
- setup.py
- tests/end_to_end/test_repo_manager.py
- tests/unit/test_cli.py
- tests/unit/test_imports.py
- tests/unit/test_repo_manager.py
Barebones implementation of repo management tool
Note: we should clarify what users' expectations are wrt adding each data object.  Are they adding a folder?  A file?  What should the semantics be?  Each object is a little different.
> 814 data tool

- tests/datadriven/test_reads.py
- tests/datadriven/test_references.py
- tests/datadriven/test_variants.py
- tests/end_to_end/test_client_json.py
- tests/end_to_end/test_repo_manager.py
- tests/paths.py
- tests/unit/test_converters.py
- tests/unit/test_repo_manager.py
> Refactor hardcoded paths into module

- tests/unit/test_simulated_stack.py
> Add a test for find VA sets by ID

- ga4gh/cli.py
- tests/end_to_end/test_repo_manager.py
> Speed up repo manager end to end test

- ga4gh/datarepo.py
- ga4gh/frontend.py
- tests/end_to_end/test_server_start.py
(Also change a public method to not be named as a private method.)
Issue #898
> Test for server startup

- ga4gh/cli.py
- tests/end_to_end/test_client_json.py
> Issue 894: Adds cli endpoint for variantsets-get

- docs/development.rst
> Document that we are now using protected branches

- ga4gh/cli.py
> Refactor of cli using addSubparser method

- docs/development.rst
- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/client.py
- ga4gh/datamodel/datasets.py
- ga4gh/datamodel/reads.py
- ga4gh/datarepo.py
- ga4gh/exceptions.py
- ga4gh/frontend.py
- ga4gh/repo_manager.py
- repo_dev.py
- requirements.txt
- setup.py
- tests/datadriven/test_reads.py
- tests/datadriven/test_references.py
- tests/datadriven/test_variants.py
- tests/end_to_end/test_client_json.py
- tests/end_to_end/test_repo_manager.py
- tests/end_to_end/test_server_start.py
- tests/paths.py
- tests/unit/test_cli.py
- tests/unit/test_client.py
- tests/unit/test_converters.py
- tests/unit/test_imports.py
- tests/unit/test_repo_manager.py
- tests/unit/test_views.py
> G2P Topic branch update

- tests/unit/test_imports.py
> "Fix" import test

- ga4gh/cli.py
- tests/end_to_end/test_repo_manager.py
- tests/unit/test_cli.py
> Safety check for cli repo manager deletion

- docs/configuration.rst
> Document repo manager

- docs/configuration.rst
- docs/development.rst
- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/client.py
- ga4gh/datarepo.py
- ga4gh/frontend.py
- tests/end_to_end/test_client_json.py
- tests/end_to_end/test_repo_manager.py
- tests/end_to_end/test_server_start.py
- tests/unit/test_cli.py
- tests/unit/test_client.py
- tests/unit/test_views.py
Updates VA branch with master. Adds repo manager documentation.
> Update VA Branch with master

- ga4gh/serverconfig.py
> Enable req/resp validation in development config

- docs/api.rst
- docs/configuration.rst
- ga4gh/datamodel/variants.py
Fixes a couple of bugs for setting timestamps and adds basic documentation.
> Update docs and fix bugs

- ga4gh/avrotools.py
- tests/unit/test_avrotools.py
- tests/unit/test_protocol_errors.py
> Make request validation failures stop choking

- ga4gh/repo_manager.py
> Don't have repo manager crash on top-level junk

- ga4gh/avrotools.py
- tests/unit/test_avrotools.py
> Don't report optional fields as missing

- ga4gh/backend.py
> Fix bad page token -> 500

- ga4gh/cli.py
- tests/unit/test_cli.py
> Make VAS Search cli argument positional

- docs/configuration.rst
- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/client.py
- ga4gh/datamodel/__init__.py
- ga4gh/datamodel/reads.py
- ga4gh/datamodel/variants.py
- ga4gh/datarepo.py
- ga4gh/frontend.py
- ga4gh/repo_manager.py
- tests/end_to_end/test_gestalt.py
- tests/end_to_end/test_repo_manager.py
- tests/unit/test_cli.py
- tests/unit/test_client.py
- tests/unit/test_faultydata.py
- tests/unit/test_repo_manager.py
- tests/unit/test_simulated_stack.py
Maintains BioSample against master. No code changes.
> Biosample update

- ga4gh/cli.py
Now you can binary search with your eyes
Issue #989
> Sort help output of scripts

- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/client.py
- ga4gh/datamodel/__init__.py
- ga4gh/datamodel/reads.py
- ga4gh/datamodel/variants.py
- ga4gh/datarepo.py
- ga4gh/frontend.py
- ga4gh/repo_manager.py
- tests/end_to_end/test_gestalt.py
- tests/end_to_end/test_repo_manager.py
- tests/unit/test_cli.py
- tests/unit/test_client.py
- tests/unit/test_exceptions.py
- tests/unit/test_faultydata.py
- tests/unit/test_repo_manager.py
- tests/unit/test_simulated_stack.py
Brings RNA branch in line with latest server updates including 0.2 release
> Rna topic branch update

- .travis.yml
- dev-requirements.txt
- docs/development.rst
- ga4gh/cli.py
- requirements.txt
- setup.py
This new test runs only on travis, normally
Issue #1008
> Test package-installed server startup

- ga4gh/serverconfig.py
I've found this additional config useful for testing.
`python server_dev.py --config SimulatedConfig`
> Add a simulated config for testing

- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/client.py
- ga4gh/datamodel/__init__.py
- ga4gh/datamodel/biodata.py
- ga4gh/datamodel/datasets.py
- ga4gh/repo_manager.py
- scripts/1kgenomes_biodata.py
- tests/end_to_end/test_client_json.py
- tests/unit/test_cli.py
- tests/unit/test_client.py
- tests/unit/test_simulated_stack.py
This PR includes tweaks proposed by @jeromekelleher and @diekhans .
Make checking for presence more verbose (`request.name -> request.name is not None`).
Refactor script for generating biodata from thousand genomes csv.
Tweak comments.
In reading over the review I noticed the same lookahead functionality needed to be implemented for searching bioSamples as well.
> Biodata review

- ga4gh/converters.py
- ga4gh/datamodel/variants.py
- requirements.txt
- scripts/download_data.py
Uses the local download facility for BAM indexes.
-1: This shouldn't be merged until pysam 0.8.5 is actually released.
> Updates for pysam 0.8.5.

- ga4gh/repo_manager.py
- tests/end_to_end/test_repo_manager.py
> Fix repo manager choking on traililng path slashes

- ga4gh/converters.py
- ga4gh/datamodel/variants.py
- ga4gh/repo_manager.py
- requirements.txt
- scripts/download_data.py
- tests/end_to_end/test_repo_manager.py
Updates SA with the latest changes from master, most notably a switch to pysam 0.9.0.
> Sequence Annotation Update

- ga4gh/datamodel/__init__.py
- ga4gh/datamodel/reads.py
- tests/datadriven/test_reads.py
- tests/unit/test_compound_ids.py
Remove readGroupId portion of RACID
Does not close #596 
See discussion in #1021
> Refactor of ReadAlignmentCompoundId

- ga4gh/datamodel/sequenceAnnotations.py
- scripts/generate_gff3_db.py
added `order by` clause to returned features, and a database indexing command to `generate_gff3_db`, as suggested by @david4096
> Rectify two minor points brought up in code review

- ga4gh/datamodel/__init__.py
- tests/end_to_end/test_gestalt.py
- tests/end_to_end/test_oidc.py
- tests/paths.py
- tests/unit/test_compound_ids.py
- tests/unit/test_views.py
Issue #1012 
(Alternative to #1022)
> Unique ids for top-level objects

- ga4gh/datamodel/__init__.py
- tests/unit/test_compound_ids.py
- tests/unit/test_views.py
> Method to generate invalid CompoundId strings

- .gitignore
> Put sqlite-generated files in gitignore

- tests/datadriven/test_sequenceAnnotations.py
Decorator to improve test methods that are written with the purpose of expecting one specific exception to be thrown
> Add ExpectException decorator

- scripts/generate_gff3_db.py
- scripts/utils.py
> Batch sql inserts for gff3 script

- .gitignore
- scripts/demo_example.py
- scripts/generate_gff3_db.py
- scripts/prepare_compliance_data.py
- scripts/utils.py
> Add import glue to scripts that import ga4gh

- ga4gh/backend.py
- ga4gh/exceptions.py
> Fix 500 if readGroupSet not mapped to referenceSet

- ga4gh/cli.py
- tests/end_to_end/test_client_json.py
- tests/end_to_end/test_gestalt.py
- tests/unit/test_cli.py
Add variantannotationsets-get to the CLI client. close #1092
> Variant annotation sets get

- deploy/config.py
- docs/configuration.rst
this is documentation to address user misunderstanding that results in https://github.com/ga4gh/server/issues/1101
> increased level of alarm about Flask DEBUG

- ga4gh/frontend.py
some nosetests are still failing.
Will close #1099
> Removed check for Debug so that we always log exceptions.

- docs/development.rst
- docs/status.rst
> Update release instructions

- ga4gh/cli.py
- ga4gh/datamodel/datasets.py
- ga4gh/datarepo.py
- ga4gh/exceptions.py
- tests/unit/test_compound_ids.py
- tests/unit/test_repo_manager.py
> Add feature set add / delete to repo manager

- ga4gh/backend.py
- ga4gh/datamodel/rna_quantification.py
Fixes typos in implementation of `featuregroup/search`
> Rna api feature group search fix

- ga4gh/datarepo.py
- ga4gh/exceptions.py
- tests/unit/test_datarepo.py
- tests/unit/test_repo_manager.py
> Add version check to data repo

- ga4gh/datamodel/reads.py
- ga4gh/datarepo.py
> Cache num(Un)AlignedBases for ReadGroupSets

- ga4gh/datarepo.py
- ga4gh/exceptions.py
- tests/unit/test_datarepo.py
> Throw exception if DB does not exist

- ga4gh/_protocol_definitions.py
- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/client.py
- ga4gh/datamodel/datasets.py
- tests/unit/test_client.py
> make datasetId a required argument for rna quantification search

- scripts/download_example_data.py
Minor mods to example data script to use import glue. Confirm that this produces working example data.
> Updated download example data script.

- ga4gh/frontend.py
- tests/unit/test_exceptions.py
> Only log exceptions if they are true server errors

- docs/installation.rst
This further addresses #821 and should close #1123 
Also added a section discussing the process and thread count settings for Apache.
> Apache installation and configuration doc update

- ga4gh/cli.py
- ga4gh/datamodel/references.py
- tests/unit/test_cli.py
> Add options to repo manager's add-referenceset

- tests/unit/test_repo_manager.py
> Duplicate removal test for objects under datasets

- docs/configuration.rst
- ga4gh/cli.py
- ga4gh/datamodel/datasets.py
> Review fixes for sql repo

- ga4gh/cli.py
> Add top-level exception handler to repo manager

- tests/end_to_end/test_repo_manager.py
> Repo manager end to end tests enabled

- tests/unit/test_repo_manager.py
> Reinstate TestVerify

- tests/end_to_end/test_gestalt.py
- tests/end_to_end/test_oidc.py
- tests/paths.py
> Eliminate hardcoded simulated ids in tests

- ga4gh/frontend.py
- ga4gh/static/robots.txt
> Add robots.txt

- ga4gh/datamodel/reads.py
- tests/paths.py
- tests/unit/test_repo_manager.py
Issue #1180 
This is the same code as #1197, except the PR is made against `master` instead of the (now-merged) `sql_repo`
> Test for incorrect data file indexes

- docs/configuration.rst
- ga4gh/cli.py
- tests/unit/test_cli.py
This is a work in progress updating the repository administration docs. Here's what it looks like on readthedocs: http://ga4gh-server-fork.readthedocs.io/en/1205-admin-cli-docs/configuration.html#data-repository
Please review this and give some feedback.
> Partial update of repository docs.

- docs/demo.rst
Adds documentation for creating a Thousand Genomes reference server to our `demo.rst`.
As the ontologies API is changing this has been left as a TODO. Helps close #1206
> Thousand genomes repository demo

- docs/configuration.rst
- docs/demo.rst
- docs/installation.rst
- ga4gh/cli.py
1. Updates docs for ontologies.
2. Bumps version number for example data so that demo will still work.
Minor refactor of the docs to put `list` before `verify`.
> Ontology docs

- docs/status.rst
Updates for the 0.3.0 section of the release notes.
> Release notes

- docs/api.rst
- ga4gh/client.py
The client API documentation is improved with variant annotation docstring.
> Add sphinx comment for variant annotation search

- ga4gh/templates/index.html
- Adds doctype
- Wraps table headers with rows
> Issue #1145: Makes index html valid

- docs/installation.rst
Adds missing 'repo.db' to installation docs.
> Fixes doc error.

- docs/status.rst
> Release notes for 0.3.1, switch to protobuf

- docs/api.rst
> Removed misleading type documentation.

- ga4gh/client.py
- tests/unit/test_client.py
[Issue 1276](https://github.com/ga4gh/server/issues/1276) 
Changed casing on features attributes to snake casing. Also includes an added function in test_client.py to test the new changes.
> Fixed features search request

- ga4gh/client.py
The docstrings were incorrect and now properly display.
> Fix docs close #1281

- docs/installation.rst
Reopening with Bettie's commits and bumping the version number of the example data. We have used these directions successfully a couple of times now.
> Mac OS X Installation Instructions

- ga4gh/datarepo.py
- tests/unit/test_data_interface.py
Issue #1213 
@jeromekelleher not at all sure if this is what you were getting at
> New end-to-end-ish test for references

- scripts/process_schemas.py
> process_schemas Make schema path required, don't infer path

- docs/api.rst
- docs/demo.rst
- ga4gh/cli.py
- ga4gh/client.py
- ga4gh/converters.py
- scripts/demo_example.py
- scripts/ga4gh_example.ipynb
- tests/end_to_end/test_client_json.py
- tests/unit/test_cli.py
- tests/unit/test_client.py
- tests/unit/test_data_interface.py
> snake_case client api

- scripts/build_test_data.py
- scripts/run_tests.py
> Run build_test_data if necessary before tests

- scripts/download_example_data.py
- scripts/generate_fasta.py
- scripts/split_fasta.py
- scripts/utils.py
> List executable requirements for scripts

- ga4gh/cli.py
> Fix not passing assembly_id arg to server from cli

- ga4gh/frontend.py
- scripts/prepare_compliance_data.py
@david4096 just adding the tsv files to the compliance test-data made one step of the compliance testing pipeline shorter since scripts/prepare_compliance_data.py already calls rnaseq2ga
> fix a couple tiny things

- scripts/prepare_compliance_data.py
`prepare_compliance_data.py` was not actually adding the rna data to the main `repo.db`, but now it is
> Rna improvements

- scripts/generate_gff3_db.py
- scripts/rnaseq2ga.py
- tests/end_to_end/test_client_json.py
- tests/unit/test_cli.py
- tests/unit/test_simulated_stack.py
- tests/unit/test_views.py
> Created signatures for missing unit tests

- scripts/generate_gff3_db.py
- scripts/rnaseq2ga.py
- tests/end_to_end/test_client_json.py
- tests/unit/test_cli.py
- tests/unit/test_simulated_stack.py
- tests/unit/test_views.py
- tests/utils.py
> Fill todos

- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/datamodel/datasets.py
- ga4gh/datamodel/rna_quantification.py
- ga4gh/datarepo.py
- scripts/prepare_compliance_data.py
- tests/datadriven/test_rna_quantification.py
- tests/unit/test_compound_ids.py
- tests/unit/test_views.py
(Kinda) depends on #1323 
Also should be merged after #1321, which fixes one of the RNA endpoints
> Simulated tests for RNA

- ga4gh/backend.py
- ga4gh/datamodel/rna_quantification.py
- ga4gh/datamodel/sequenceAnnotations.py
- ga4gh/sqliteBackend.py
- tests/unit/test_data_interface.py
- tests/unit/test_sql_backend.py
- tests/unit/test_views.py
Issue #1330
Also:
- Added tests for sqliteBackend
- Refactored RNA to make bulk db fetches on-demand
- Renamed some methods
The paging strategy introduced here should be generalized to other similar sql-based endpoints in a future refactor.
@jeromekelleher
> Fix paging for expression levels search

- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/datamodel/genotype_phenotype.py
- ga4gh/datamodel/genotype_phenotype_featureset.py
- ga4gh/datamodel/sequenceAnnotations.py
- ga4gh/frontend.py
- ga4gh/gff3Parser.py
- scripts/build_test_data.py
- scripts/prepare_compliance_data.py
- tests/datadriven/test_genotype_phenotype.py
- tests/end_to_end/test_g2p.py
- tests/unit/test_cli.py
- tests/unit/test_imports.py
> Add g2p cli tests

- ga4gh/datarepo.py
> Emit error when attempting to delete in use refset

- tests/unit/test_converters.py
- tests/utils.py
Issue #1336
Pulled in the changes in `tests/utils.py` from the `rna` branch
> Silence spam output from noisy test

- ga4gh/datamodel/rna_quantification.py
- scripts/rnaseq2ga.py
Fix threshold to be closed to reflect schemas.
Use read group set name from control file to find read group IDs.
> RNA Update

- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/client.py
- ga4gh/datamodel/genotype_phenotype.py
- ga4gh/datarepo.py
- ga4gh/frontend.py
- scripts/prepare_compliance_data.py
- tests/datadriven/test_genotype_phenotype.py
- tests/end_to_end/test_client_json.py
- tests/unit/test_cli.py
- tests/unit/test_client.py
- tests/unit/test_data_interface.py
- tests/unit/test_repo_manager.py
- tests/unit/test_simulated_stack.py
- tests/unit/test_views.py
Also:
- stylistic fixes
- deleted dead code
- renamed class
- added test stubs for simulated stack
@bwalsh
> tests for g2p

- ga4gh/cli.py
- ga4gh/datamodel/datasets.py
- ga4gh/datarepo.py
- ga4gh/exceptions.py
- scripts/build_test_data.py
- tests/end_to_end/test_repo_manager.py
- tests/paths.py
- tests/unit/test_cli.py
- tests/unit/test_repo_manager.py
> G2p repo tests

- ga4gh/datamodel/rna_quantification.py
> fixed unhandled not found exception

- docs/configuration.rst
Documents the process for adding RNA quantification data to the datarepo.
> Additional RNA ETL documentation (WIP)

- tests/datadriven/test_genotype_phenotype.py
refactor dict for flake8 complaint
> refactor test_genotype_phenotype.py for flake8 complaint

- ga4gh/cli.py
- scripts/build_test_data.py
- tests/end_to_end/test_client_json.py
- tests/unit/test_client.py
- added dataset info arg to cli for repo manager
- added force arg to build_test_data script
- changed default value for feature set search arg
Issue #1290
> Feature(Sets) tests

- ga4gh/backend.py
- ga4gh/cli.py
- ga4gh/datamodel/genotype_phenotype_featureset.py
- ga4gh/datamodel/sequenceAnnotations.py
- tests/datadriven/test_sequenceAnnotations.py
- tests/end_to_end/test_client_json.py
- tests/unit/test_data_interface.py
> Fix Feature pagination logic

- scripts/prepare_compliance_data.py
ensure g2p test data copied into output directory
> prepare compliance: ensure g2p test data copied into output directory

- docs/configuration.rst
- ga4gh/backend.py
- ga4gh/exceptions.py
- ga4gh/frontend.py
- ga4gh/serverconfig.py
- tests/unit/test_exceptions.py
> Remove irrelevant RESPONSE_VALIDATION config param

- docs/configuration.rst
This PR:
* no new functionality
* bug fix: add documentation for phenotypeassociationset
Addresses #1383
> add documentation for phenotypeassociationset

- ga4gh/datarepo.py
> Adds prints of rna information to the list command

- ga4gh/client.py
- tests/unit/test_client.py
This PR addresses a mismatch between the paths used in the client and the frontend
Bug fixes:  #1407
> align paths between the client and front end

- ga4gh/cli/repomanager.py
- ga4gh/repo/rnaseq2ga.py
solves the problem of RSEM output columns changing with datatype, improves readability and is overall better
> convert rnaseq2ga to use csv module

- docs/demo.rst
> Add docs about ga4gh_client package

- ga4gh/cli/client.py
> Cleaned up client Feature formatting

- ga4gh/datamodel/genotype_phenotype.py
No new features are included in this PR
Bug fix:   the feature_ids returned in the FeatureAssociationResponses were not obfuscated
> ensure that feature_ids are obfuscated. closes #1413

- ga4gh/cli/repomanager.py
- ga4gh/repo/rnaseq2ga.py
- scripts/encode2ga4gh.py
- scripts/prepare_compliance_data.py
- tests/paths.py
(These are changes that can be made in any case, setting aside design questions about RNA)
- add primary keys to RNA tables
- camelcase RNA names
- refactor paths.py
> Improvements from #1386

- docs/development.rst
- docs/installation.rst
> Add link to mac os installation docs

- ga4gh/cli/repomanager.py
Issue #1423
Same changes as ga4gh/server#1424
Real author is @kozbo
> Fix remove-rnaquantificationset command

- ga4gh/cli/repomanager.py
- ga4gh/repo/rnaseq2ga.py
> fix incorrect naming in add-rnaquantification

- docs/installation.rst
Close #1438 and close #1428 
Thanks @thomasd-gen
> Installation instructions fixes

- ga4gh/repo/rnaseq2ga.py
Resolves #1436 
Increases `batchSize` to 2000 and restricts `featureSetName` lookup to the list passed into `rnaseq2ga()`
With these changes a test dataset load went from 6 minutes (37K entries with feature lookup) to 12 seconds (37K entries no feature lookup) on an underpowered laptop
> performance fixes for rna import

- ga4gh/frontend.py
I came across the 'configure' function, and it seems like it does important work, and is also not documented.  It's a long function too.
I read the whole thing, and found that this portion can be isolated out cleanly, and so I did just that.
> Refactor "configure" function.

- tests/end_to_end/test_client_json.py
> Reenable test_client_json.py

- dev-requirements.txt
- ga4gh/server/gff3.py
- scripts/prepare_compliance_data.py
- scripts/server_benchmark.py
- tests/unit/test_oidc.py
Close #1466
Add flake version output to travis.
Pin flake version.
Fix new flake rules.
> Fix flake problems with travis

- ga4gh/server/backend.py
Avoids building the entire list before sending back a response. The same should probably be done to the RNA quantifications generator, but would require adding a get-by-index functionality to the SqliteRnaQuantificationSet.
We should strive to use SQL to handle paging and iterating. When the number of items gets very large, this solution, though fast at request time, will take longer and longer to start as we load much of the SQLite database into memory.
Close #1316
> Improve read group set generator close #1316

- docs/configuration.rst
- ga4gh/server/frontend.py
- ga4gh/server/serverconfig.py
- tests/end_to_end/server.py
- tests/unit/test_oidc.py
There were a few bugs in the OIDC implementation that prevented it from storing the user sessions properly.
> Fixed OIDC Authentication

- .travis.yml
- README.txt
> Increase coverage percent

- .travis.yml
- MANIFEST.in
- constraints.txt
- dev-requirements.txt
- docs/development.rst
- ga4gh/server/protocol.py
- requirements.txt
- setup.py
- tools/travis-install-protoc.sh
Remove private API calls, close #1471 
Note pointing to a development branch of the client. PR for same change in client can be found [here](https://github.com/ga4gh/ga4gh-client/pull/35)
> Change to protobuf3.1, add constraints.txt

- constraints.txt
- docs/datarepo.rst
- ga4gh/server/backend.py
- ga4gh/server/cli/repomanager.py
- ga4gh/server/datamodel/__init__.py
- ga4gh/server/datamodel/bio_metadata.py
- ga4gh/server/datamodel/datasets.py
- ga4gh/server/datamodel/reads.py
- ga4gh/server/datamodel/rna_quantification.py
- ga4gh/server/datamodel/variants.py
- ga4gh/server/datarepo.py
- ga4gh/server/exceptions.py
- ga4gh/server/frontend.py
- ga4gh/server/protocol.py
- ga4gh/server/repo/rnaseq2ga.py
- scripts/prepare_compliance_data.py
- tests/end_to_end/test_client_json.py
- tests/end_to_end/test_repo_manager.py
- tests/unit/test_bio_metadata.py
- tests/unit/test_cli.py
- tests/unit/test_data_interface.py
- tests/unit/test_simulated_stack.py
Rename BioSample to Biosample. Propagation of ga4gh/schemas#697.
> Biosample 1394

- scripts/demo_example.py
Just noticed that this script was out of date with respect to some of the newer changes. Minor stuff, but it works now.
Updated client path and attribute names.
> Fixup demo_example script

- constraints.txt
- docs/status.rst
- requirements.txt
> add release notes for the 0.3.5 release

- constraints.txt.default
- tests/unit/test_constraints.py
> Prevent check-ins of non-default constraints.txt

- ga4gh/server/datamodel/rna_quantification.py
The rnaseq2ga pull request (#1564) caused a problem with compliance. This fixes it.
> fixed problem

- constraints.txt
- constraints.txt.default
- docs/development.rst
@david4096 after these changes are approved I will make similar changes in the constraints.txt of the other repositories.
> Document auto-releases, constraint instructions

- constraints.txt
- ga4gh/server/datamodel/variants.py
- tests/datadriven/test_variants.py
Server code for PR ga4gh/schemas#777 adding fields for variant filters.
> add filters

- constraints.txt
- ga4gh/server/datamodel/variants.py
- tests/datadriven/test_variants.py
Implements ga4gh/schemas#772 (and ga4gh/schemas#827)
> implemented structural variant fields

- .travis.yml
- CONTRIBUTING.md
- README.txt
- dev-requirements.txt
- docs/demo.rst
- docs/development.rst
- docs/installation.rst
- docs/status.rst
- ga4gh/server/cli/repomanager.py
- ga4gh/server/templates/landing_message.html
- requirements.txt
- setup.py
- tests/unit/test_converters.py
- tests/unit/test_oidc.py
> Change URLs to prepare for GitHub rename
