ga4gh/ga4gh-server

README.txt
ga4gh/server/__init__.py
ga4gh/server/config.py

Read a set of configuration values out of a file (config.py).
Checks the environment variable GA4GH_CONFIGURATION for the name of the configuration object in that file to use; default is ga4gh.server.config:Config.
Addresses issue https://github.com/ga4gh/server/issues/61.
This initial version only provides the default configuration, but in prototyping profiling I've created subclasses of Config, set new values on them, used the environment variable to select between them, and verified that the correct config was selected.

Externalize configuration.

---

ga4gh/backends.py
ga4gh/cli.py
ga4gh/server/__init__.py
ga4gh/server/views.py
tests/__init__.py
tests/test_backends.py
tests/test_views.py

This is an early PR for comments and discussion. 
Here is a first pass at implementing paging in a general way. The idea is that the `Backend` object gets a call to `searchX` and then delegates this to `runRequest`, which does the paging in a general way. `runRequest` gets a bunch of parameters which allow it to do this, the key one being `objectGenerator`. This is an iterator over all of the objects specified by the request.
The tricky bit is dealing with page tokens. To deal with this, the generator yields pairs of values `(object, nextPageToken)`, which it's the generators responsibility to manage. It's easy in this case, but it'll be more trick when I move on to variants.
Before doing this, I'd like to get some feedback. What do people think of the general outline?

Unified paging

---

ga4gh/__init__.py

The version number is currently set arbitrarily to 0.5.0. The idea originally was to follow the API version number that we were implementing. However, this is less important now that we have automated generations of schemas from a specific protocol version, and we can find out what version of the protocol we are implementing using `ga4gh.protocol.version`.
We should therefore choose a different version number. Since we are currently pre-alpha, 0.1.0a1 seems a good choice. Any thoughts?

Changed version number.

---

ga4gh/backends.py
ga4gh/client.py
ga4gh/protocol.py
tests/test_backends.py
tests/test_schemas.py
tests/test_views.py

These changes should increase readability and performance. JSON serialization shouldn't have any semantic changes, though equality testing will now exit early. The early exit should yield much better performance when dealing with large and complicated classes. This patch also removes the deprecated toJSON method because we are pre-release and there really isn't a reason to have deprecated code hanging around.
I'm hoping that there might be some other suggestions as to how to improve clarity here. I spent some time trying to create a unified interface to serialization and deserialization, but I was unable to get anything that I thought was actually more clear. The level of duplication here is fairly minimal and so far I've chosen the 15 lines of slight duplication devil vs 30 lines of …

Improve JSON serialization and equality testing.

---

ga4gh/frontend.py
ga4gh/server/__init__.py
ga4gh/serverconfig.py
tests/test_views.py

This PR moves the `ga4gh.server.config.py` file to `ga4gh.serverconfig.py`, completing the removal of the `server` package. Also adds a stub `TestConfig` class used to set up flask frontend tests.
This fixes the current build breakage in Travis, and should be small and uncontroversial, so it would be good to vote and merge this as soon as possible.

Added testing config and moved default config file

---

ga4gh/backend.py
requirements.txt
server_benchmark.py

If "--profile heap" is passed to server_benchmark.py, prints out
a heap snapshot inside Backend.runSearchRequest(), which currently
has high peak memory allocation.
Adds a dependency on guppy (currently 0.1.10).
Addresses https://github.com/ga4gh/server/issues/46.

Heap profiling inside server_benchmark

---

ga4gh/_protocol_definitions.py
ga4gh/protocol.py
scripts/generate_schemas.py
tests/test_client.py
tests/test_schemas.py

Replaces `__dict__` with `__slots__` for all ProtocolElement subclasses,
leading to significant space savings. Switches unit test from `__dict__`
to `__slots__`.
Addresses https://github.com/ga4gh/server/issues/92
-------
This cuts memory usage during our benchmark variants search by 250MB.
In master, server_benchmark.py --profile heap shows:
Partition of a set of 1253757 objects. Total size = 402956592 bytes.
```
Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
0 250400  20 262419200  65 262419200  65 dict of ga4gh._protocol_definitions.GACall
1 250500  20 70140000  17 332559200  83 dict (no owner)
2 501502  40 54216624  13 386775824  96 list
3 250400  20 16025600   4 402801424 100 ga4gh._protocol_definitions.GACall
4    100   0   104800   0 402906224 100 dict of …
```

Use __slots__ for ProtocolElements

---

.travis.yml
ga4gh/cli.py
ga4gh/datamodel/reads.py
ga4gh/datamodel/references.py
ga4gh/frontend.py
requirements.txt
tests/test_backends.py
tests/test_cli.py
tests/test_client.py
tests/test_end_to_end.py
tests/test_exceptions.py

Flake8 combines pep8 checks with some other lint checks. See http://flake8.readthedocs.org/en/2.2.3/ for details. These are the minimum changes required to get flake8 checks passing.
This also fixes a bug in the configure function in `frontend.py` which flake8 caught.

Added support for flake8 checks.

---

STYLE.md

Breaking out this change from #108 
I'd like to advocate disobeying the part of PEP8 that says: "Note: When using abbreviations in CapWords, capitalize all the letters of the abbreviation. Thus HTTPServerError is better than HttpServerError." Noun boundaries are difficult to parse with all-caps acronyms, especially with a variable name that has multiple acronyms. For instance:
HttpClient is easier to read than HTTPClient
HttpApiClient is easier to read than HTTPAPIClient
PEP8 doesn't offer any rationale for the "Note" recommendation.

Change style guide abbreviations policy

---

ga4gh/frontend.py
ga4gh/frontend_exceptions.py
ga4gh/templates/index.html
requirements.txt
tests/test_exceptions.py
tests/test_views.py

Displays the following info:
```
GA4GH reference server 0.5.1
Operations available
Method	Path
POST	/callsets/search
POST	/readgroupsets/search
POST	/reads/search
GET	/references/<id>
GET	/references/<id>/bases
POST	/references/search
GET	/referencesets/<id>
POST	/referencesets/search
POST	/variants/search
POST	/variantsets/search
Uptime
Running since 18 minutes ago (03:04:56 03 Feb 2015)
```
Issue #111

Adds html info page served at /

---

.travis.yml

Since #136 we don't need to make an exception for flake8 import checks (using # NOQA instead, which is much better).

Removed unnecessary flake8 exception.

---

ga4gh/backend.py
ga4gh/cli.py
ga4gh/client.py
ga4gh/frontend.py
ga4gh/protocol.py
server_benchmark.py
tests/test_backends.py
tests/test_cli.py
tests/test_client.py
tests/test_end_to_end.py
tests/test_schemas.py
tests/test_views.py

Issue #135 
Renamed the following names:
```
- toJSONString
- handleHTTPPost
- handleHTTPOptions
- printJSONMessage
- fromJSONString
- fromJSONDict
- toJSONDict
- HTTPClient
```

Renamed capitalized acronyms to camel-case

---

README.txt

We changed the variantId option from -v to -V previously to avoid conflicts with the verbose flag, but didn't update the README to reflect that.

Change the README so that the example usage works

---

ga4gh/_protocol_definitions.py
scripts/process_schemas.py

issue #115 
When generating the embedded text representing the JSON schema of a protocol element, the process_schemas.py script pipes the text through fmt to wrap the text. The textwrap module from the standard library provides a much better way to do this.

use textwrap module to replace fmt in process_schemas.py

---

setup.py

This allows the server to serve html files from the installed
ga4gh package.
Issue #139

Set zip_safe in setup.py to False

---

ga4gh/backend_exceptions.py
ga4gh/datamodel/variants.py
ga4gh/frontend.py
ga4gh/frontend_exceptions.py
tests/unit/test_exceptions.py

The payload that comes back from an exception with a defined more-specific message is now something like:
```
{
"errorCode": 4,
"message": "callSet 'HG03279' not in variantSet '1000g_2011'"
}
```
Issue #160

Add backend_exceptions

---

ga4gh/backend.py
ga4gh/datamodel/reads.py
ga4gh/datamodel/references.py
ga4gh/datamodel/variants.py
ga4gh/frontend.py
tests/unit/test_backends.py
tests/unit/test_views.py

This PR is intended to add initial support for the top level objects in the reference and read hierarchies. It adds to the existing infrastructure in the simplest and least intrusive way, and should not be seen as 'finished work'.
The biggest difference here from a user perspective is that I've changed the required structure of the input `dataDir`. This was assumed to contain variantSets, and must now contain three directories: `variants`, `reads` and `references`. This is not the structure that we ultimately want (references should be independent of datasets), but it will get us going for now. If we agree on this structure I'll update the `ga4gh-example-data` set so that it follows this new layout.
There is no testing of the new code, since we don't have any example or test data to test …

Basic infrastructure for top-level objects.

---

ga4gh/client.py

Output in debug mode looks like:
```
ga4gh.client: POST https://www.googleapis.com/genomics/v1beta2/variants/search  
ga4gh.client: json request:
ga4gh.client: {
"callSetIds": [],
"end": 51005492,
"pageSize": 1,
"pageToken": null,
"referenceName": "22",
"start": 51005491,
"variantName": null,
"variantSetIds": [
"10473108253681171589"
]
}
ga4gh.client: json response:
ga4gh.client: {
...
```
Issue #169

Client logs json requests in debug mode

---

ga4gh/cli.py

The recent change to the default value for `workarounds` left the client program in a broken state, as a lot of code assumed that the `workarounds` variable was always a string and not None. This changes the behaviour back, and fixes the bug.
Also changed the default value for referenceName to `1`, as `chrSim` was an ancient and useless relic.

Fixed workarounds bug.

---

ga4gh/frontend.py
ga4gh/frontend_exceptions.py
tests/unit/test_views.py

To ensure correctness, we will probably need to do the same with just about every 4xx error message (at least), but I think we can just add these as time goes on and people hit html erroneously.
Issue #166

404s and 405s now return json instead of html

---

.travis.yml

This won't change how coverage is computed on Travis (presumably because there aren't any cached coverage files lying around in a fresh install), but it will change local numbers to be accurate when using `run_tests.py`
Issue #197

Delete cached coverage before computing coverage

---

README.txt
ga4gh/serverconfig.py
requirements.txt

Fixed the README so that example queries run. Also changed the default configuration to turn off validation by default so that queries run against tabix indexed data run.
(Note, there is some diff-noise in the README introduced by trailing whitespace being removed.)

Fixed README examples and queries on example data.

---

ga4gh/backend.py
ga4gh/cli.py
ga4gh/frontend.py
ga4gh/serverconfig.py
tests/unit/test_cli.py

This PR removes the mandatory DATADIR argument from the server CLI, and moves all configuration into the flask config space. This is an essential step towards deployability.
For development, we add a default configuration that we invoke from the CLI that makes the default data source ga4gh-example-data. This should make developers lives easy. We can override this with a config file specified on the command line though.
This will be updated and rebased once #212 has been merged. Feedback welcomed!

Remove datadir arg

---

ga4gh/datamodel/variants.py
tests/datadriven/__init__.py
tests/datadriven/test_references.py
tests/datadriven/test_variants.py

Initial POC for data driven tests in the HtslibVariantSet.  Adds the `self.assertEqual` method to the data driven tests, which might solve our issues with not using unittest.
This PR depends on #208.

Htslib data driven tests

---

.travis.yml

On my local system installing into a new virtualenv off of this branch successfully skips the pysam compile step, which is the most timely step in our build.  These changes drop the build time on my system from around 5 minutes to under 30 seconds. 
Wheels are OS/arch dependent, to an extent.  The one that I built doesn't work on the Travis environment, which uses a 64 bit Ubuntu build.  We just need to get a wheel that the Travis environment finds acceptable, which might take a bit of guess-and-check (building the wheel on an identical Ubuntu environment would work).    The wheel we need can be created with the command `pip wheel pysam`.
We would also need to check in a new version of the wheel whenever pysam had changes we wanted to incorporate.
Questions: 
- is it acceptable to check …

wheels WIP

---

scripts/utils.py

pysam provides the capability to call samtools methods directly...
we should use that instead of using shell commands!

Replace samtools index runCommand with pysam call

---

tests/unit/test_backends.py
tests/unit/test_variants.py

As we remove wormtable, we need to make sure that we retain all the tests that we have in tests/unit/test_backends.py in some form. This PR starts the process by moving the trivially seperable unit tests for genotype conversion into an independent module for variant unit tests.

Moved genotype unit tests into new module.

---

README.txt

Restart server with `sudo service apache2 restart` on default apache2 install on ubuntu.

Typo fixed in README deploy instructions.

---

tests/unit/test_views.py

The new version of Flask-CORS doesn't seem to like our tests. We should figure out why. In the meantime, this update disables the test in question so that our other builds complete.

Temporary workaround for broken cors tests.

---

ga4gh/cli.py

DEBUG is allways true in the CLI, regardless of the value specified in your config. This fixes the problem.

Fixes DEBUG override in CLI.

---

tests/unit/test_views.py

Not sure how this test ever worked... maybe there was a bug in a previous version of the library.
Issue #278

Fix CORS test

---

ga4gh/datamodel/variants.py
tests/unit/test_backends.py

New `TestAbstractBackend` class introduced in `unit/test_backends.py`,
gathers together backend implementation independent logic,
`TestSimulatedBackend` and `TestWormtableBackend` classes inherit from it.
`TestPaging` is a new subclass of `TestSimulatedBackend`. This setup
should provide a clean migration path out of Wormtable for testing backend.
For now, I could only pull `TestVariantSets.testPagination()` out of 
`TestWormtableBackend`, as `SimulatedBackend` only provides mock objects
for `VariantSet`s. As `SimulatedBackend` grows, the other tests in `test_backends.py`
can be pulled out as well.
I could technically pull out `TestVariantSets.testIds()` now as well, but this doesn't fit
the new `TestPaging` class's focus on pagination. 
Addresses issue #241

Paging test moved from wormtable to simulated backend.

---

ga4gh/_protocol_definitions.py
ga4gh/backend.py
ga4gh/frontend.py
ga4gh/protocol.py
ga4gh/serverconfig.py
scripts/process_schemas.py
server_benchmark.py
tests/unit/test_backends.py
tests/unit/test_schemas.py

There are some serious issues with the current paging implementation:
1. It is trivial to perform a DOS/memory starvation attack. Simply provide a very large page size, and we will blindly try to fill it up until memory runs out.
2. There is no easy way to control latency. The only knob we have is the pageSize, but this is very crude as not all obejcts are equal. The pageSize controls the number of objects a page contains, _not_ the absolute size of the page in terms of bytes. Since objects like `Variant` can contain an arbitrarily large number of embedded objects (`Call` in the case of `Variant`) there's no way to know just how much memory we require.
Problem (1) could conceivably be tackled just by using the pageSize, but it would always be slightly tricky (what if there was 100k …

Adaptive pagesize and max request size.

---

ga4gh/backend.py
ga4gh/cli.py
tests/unit/test_backends.py
tests/unit/test_views.py

This is a straightforward fix for a logic bug in the variants/search method. Issue #301 states that this should be fixed by reusing the code from reads/search. However, this proved to be a little complex, and it seemed better to fix this bug quickly in a simple way.
We have also reduced to handling exactly one variant set only. The existing implementation was incorrect (see issue #180), and we had almost no test coverage on the multi-container case, so it seemed better to explicitly only support the case that works.
This  solves #180.

Simple fix for variants-search.

---

scripts/update_data.py

The example data has been updated with an improved data set, and is available to download at http://www.well.ox.ac.uk/~jk/ga4gh-example-data.tar. It is an uncompressed tarball now, as all the internal data is already compressed. This PR updates the downloader script to take this into account.

Changed to uncompressed tarball.

---

ga4gh/backend.py
ga4gh/datamodel/reads.py
ga4gh/frontend.py
ga4gh/templates/index.html

This updates the info frontpage to include information on readgroupsets. Here is a snapshot:
```
GA4GH reference server 0.1.0a2
Protocol version 0.5.1
Operations availableMethod	Path
POST	/v0.5.1/callsets/search
POST	/v0.5.1/readgroupsets/search
POST	/v0.5.1/reads/search
GET	/v0.5.1/references/<id>
GET	/v0.5.1/references/<id>/bases
POST	/v0.5.1/references/search
GET	/v0.5.1/referencesets/<id>
POST	/v0.5.1/referencesets/search
POST	/v0.5.1/variants/search
POST	/v0.5.1/variantsets/search
Uptime
Running since a second ago (14:49:27 31 Mar 2015) 
ConfigurationKey	Value
DEBUG	True
REQUEST_VALIDATION	False
RESPONSE_VALIDATION	True
Data
VariantSets
1kg-phase1
1kg-phase3
ReadGroupSets
low-coverage
low-coverage:HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522 …
```

Added data summary for reads.

---

docs/source/development.rst

The docs are currently breaking, which is causing builds to fail. This fixes the problem by making links anonymous.

Fixed docs build.

---

ga4gh/datamodel/__init__.py
ga4gh/datamodel/reads.py
ga4gh/datamodel/variants.py
ga4gh/exceptions.py
tests/unit/test_sanitizer.py

Addresses issue #232. 
The idea here is push code that is common to variants and the reads datamodel code into a new mixin,  `PysamDatamodelMixin`. 
Also fixes a bug in the exceptions for missing VariantSets.

Generalised the datamodel file system code.

---

deploy/Dockerfile
docs/source/installation.rst

This PR is a continuation of PR #326 which address issue #305 by adding a Dockerfile and documentation.
--
ACK: Just seeing docs on https://github.com/ga4gh/server/pull/337 about committing - sorry for the poorly named branch.

added Dockerfile

---

ga4gh/_protocol_definitions.py
ga4gh/avrotools.py
ga4gh/backend.py
ga4gh/cli.py
ga4gh/client.py
ga4gh/datamodel/reads.py
ga4gh/datamodel/references.py
ga4gh/datamodel/variants.py
tests/datadriven/test_reads.py
tests/datadriven/test_references.py
tests/datadriven/test_variants.py
tests/end_to_end/test_gestalt.py
tests/unit/test_avrotools.py
tests/unit/test_backends.py
tests/unit/test_client.py
tests/unit/test_converters.py
tests/unit/test_protocol_errors.py
tests/unit/test_schemas.py
tests/unit/test_simulated_stack.py
tests/unit/test_views.py

This is the first of a short series of PA's intended to update the protocol definitions from
0.5.1 to the most recent version found on ga4gh/schemas.
Since graph reference support introduced a host of changes, this PR aims to bring
the server protocols up to the last commit before graph support was merged into the schemas repo.
This specific PR includes removing the GA prefix, introduction of new ontology entities, as well as minor semantic changes (especially with union types). 
The state of this PR is very rough, and several tests are currently failing (they've been decorated so as to be skipped). The intention, as discussed with @jeromekelleher and @dcolligan is to fix these failing tests through a followup series of issues/short PR's.

protocols updated to reflect schemas commit e6d6074

---

.dockerignore
.whiskey/action_hooks/pre-build
Dockerfile
deploy/application.wsgi
deploy/config.py
deploy/variants/centos-demo-noapache/Dockerfile
deploy/variants/demo/Dockerfile
deploy/variants/ubuntu-demo-apache/Dockerfile
docs/source/installation.rst

1) ./Dockerfile, which builds the server with mod_wsgi-express. Data and config.py are not placed.
2) demo/Dockerfile, which adds the example data and config.py to 1)
3) demo_light/Dockerfile, which builds only the python, as the demo in
existing docs

Add support for Docker

---

ga4gh/frontend.py
tests/unit/test_views.py

Rationale:
Some might think /{version} not / is the base url and fire off a browser request to it.  Easy mistake to make.

Make GET /{version} return the HTML page as well

---

ga4gh/frontend.py

Issue #385 
This is so the paths don't appear in the HTML display, which can be confusing to a new user when s/he tries to hit them and they don't work.  We're not losing any functionality here, and can look up this commit and incorporate its reversion when we actually do want to implement these paths.

Take out unused paths

---

ga4gh/exceptions.py
tests/unit/test_exceptions.py
tests/unit/test_imports.py

Error messages now look like:
```
"Request '{u'referenceId': None, u'end': None, u'readGroupIds': [], u'pageSize': None, u'pageToken': None, u'start': u'thisIsWrong'}' is not a valid instance of <class 'ga4gh._protocol_definitions.SearchReadsRequest'>; invalid fields: {u'start': u'thisIsWrong'}"
```
Issue #382

Improve request/response failure error messages

---

ga4gh/datamodel/variants.py
tests/datadriven/test_variants.py

solving issue #396 by adding description field to metadata
TODO: 
testVariantSetMetadata() currently uses python module pyvcf to test against pysam, however, pyvcf is not reading any metadata at all. filed an separate issue #406

updated vcf metadata parser to get description field 

---

docs/source/installation.rst
scripts/demo_example.py

Add example of linked containers. Add demo script
[Rendered docs](http://umms-ga4gh-server.readthedocs.org/en/2015-05-13_update_docker_docs/installation.html#deployment-on-docker)

Update dockerhub repo name to point to org.

---

ga4gh/_protocol_definitions.py
ga4gh/backend.py
ga4gh/cli.py
ga4gh/client.py
ga4gh/datamodel/datasets.py
ga4gh/exceptions.py
ga4gh/frontend.py
ga4gh/templates/index.html
tests/end_to_end/test_gestalt.py
tests/unit/test_backends.py
tests/unit/test_cli.py
tests/unit/test_client.py
tests/unit/test_datasets.py
tests/unit/test_response_generators.py
tests/unit/test_simulated_stack.py
tests/unit/test_views.py

TODO:
- the end-to-end tests are failing because our default for variants-search is to first to a variantsets-search to request all of the variantsets of the server.  With multiple datasets, however, we must also specify what dataset's variantSets we want (and we have a self-imposed restriction right now of only being able to request one dataset).  Knowing this datasetId is impossible without querying the server before the variantsets-search request, so we need to request it from the server.  There is a `/datasets/search` path specified in the most current schema, but it is not in our `_protocol_definitions.py`.  We can't get the response object into `_protocol_definitions.py` without running `process_schemas.py` on the most recent schemas, which is a questionable idea in and of itself …

Dataset support

---

ga4gh/backend.py
ga4gh/datamodel/__init__.py
ga4gh/datamodel/reads.py
tests/unit/test_sanitizer.py

Reopening #456 against the release-0.1 branch
- fix referenceId and referenceName not getting passed correctly
- sanitize pysam getrname calls
Issue #455

Fixes for reads/search

---

ga4gh/frontend.py
tests/unit/test_views.py

Issue #449
Kinda weird this wasn't caught by the `tests.unit.test_views:TestFrontend.test404sReturnJson` test.  Not sure what accounts for the behavior discrepancy between the test and requesting the nonexistant page in a browser...

Certain non-mapped URLs now return 404s

---

ga4gh/datamodel/__init__.py
ga4gh/datamodel/reads.py
tests/unit/test_sanitizer.py

Cherry-pick of 9f68e90c4c9a5206d0c80da5ae477f5a38074834
- sanitize pysam getrname calls
Issue #455

Forward-port of 'Fixes for reads/search'

---

ga4gh/exceptions.py
ga4gh/frontend.py
tests/unit/test_views.py

As of schema version 84927c4cc9a74a3db310026de8b31cdca8bbcfd0
Issue #431 
It would probably be better to use the flask route syntax instead of the `re` module, but I'm not sure if Flask supports matching routes outside an app context...

Make unimplemented paths defined in schema 501

---

docs/source/demo.rst
requirements.txt
setup.py

The master branch was broken by a new version of flask-api on pypi. We don't use flask-api, so dependency removed. Also, the documentation for the demo was invalidated by the recent support for datasets. Sort of fixed.

fixed some demo docs, and the build

---

.travis.yml
docs/source/demo.rst

Also fix error in docs wrt red hat setup
Strangely, the `make` command doesn't fail when the error was present, but it does emit the following:
```
...
reading sources... [100%] introduction
/Users/dannyc/ga4gh/server/docs/source/demo.rst:34: ERROR: Error in "code-block" directive:
maximum 1 argument(s) allowed, 7 supplied.
.. code-block:: bash
$sudo dnf install python-devel python-virtualenv zlib-devel
looking for now-outdated files... none found
...
```

Build docs as part of CI and run_tests.py

---

ga4gh/frontend.py
ga4gh/templates/index.html

Issue #472 
'Operations available' section now looks like:
```
Method	Path
GET	/0.6.e6d6074/references/<id>
GET	/0.6.e6d6074/references/<id>/bases
GET	/0.6.e6d6074/referencesets/<id>
POST	/0.6.e6d6074/callsets/search
POST	/0.6.e6d6074/datasets/search
POST	/0.6.e6d6074/readgroupsets/search
POST	/0.6.e6d6074/reads/search
POST	/0.6.e6d6074/references/search
POST	/0.6.e6d6074/referencesets/search
POST	/0.6.e6d6074/variants/search
POST	/0.6.e6d6074/variantsets/search
```

Only display live routes on html page

---

ga4gh/backend.py
ga4gh/datamodel/datasets.py
ga4gh/exceptions.py
tests/end_to_end/test_gestalt.py
tests/end_to_end/test_remote_fetch.py
tests/unit/test_backends.py
tests/unit/test_response_generators.py
tests/unit/test_views.py

A compound id is the former id plus the dataset id it belongs to
Issue #453

Use compoundIds for variantSets and readGroupSets

---

ga4gh/backend.py
ga4gh/cli.py
ga4gh/client.py
ga4gh/converters.py
ga4gh/frontend.py
tests/unit/test_cli.py
tests/unit/test_client.py
tests/unit/test_simulated_stack.py
tests/unit/test_views.py

This PR:
1. Adds the GET endpoint for variantsets, along with various infrastructure for that; and 
2. Adds the framework for ga2vcf.
The background for this is that @bioinformed asked me to provide an outline to give him a better idea of what we need for his VCF write support in pysam. Once this PR has been merged I'll create an issue for filling in the gaps in ga2vcf, which I'll assign to @bioinformed (if he still wants to work on it!).

Added getVariantSet + framework for ga2vcf.

---

oidc-provider/INSTALL.txt

This is related to issue #448. I added instructions for Ubuntu only but we would need to add the requirements for an installation on Mac OS X.

oidc-provider requirements

---

docs/source/demo.rst
docs/source/development.rst

Since bringing some extra requirements for the OIC extension, we need some extra low-level libraries to make it compile. We've hit this issue already in #484.
This updates the documentation to include the required package for ubuntu. I'll open an issue to update the docker configs as well.

Updated docs for new lib requirement.

---

ga4gh/cli.py
ga4gh/sidegraph.py
setup.py
tests/unit/test_sidegraph.py

2 changes to subgraph endpoint:
sends position,radius as ints
fixes off-by-one errors in segment length and end position

Changes to Subgraph Endpoint in Graph Branch

---

tests/unit/test_oidc.py

Purpose of this PR is an initial validation of the github workflow as well as a simple test of oidc-provider mimetypes dependency.

test to validate mimetypes config, a dependency of oidc-provider

---

ga4gh/backend.py
ga4gh/frontend.py
tests/unit/test_backends.py

This is a purely syntactic refactor and reorganisation to make the backend easier to work with. The basic idea is to change all of the API entry points to start with ``runX``, so that we can distinguish them from internal methods.
Also reorganised the class so that methods are grouped together more logically for readability.

Refactor backend to make application edge clearer.

---

ga4gh/backend.py
ga4gh/cli.py
ga4gh/client.py
ga4gh/frontend.py
tests/unit/test_cli.py
tests/unit/test_client.py
tests/unit/test_views.py

Tests to come.
```
$ python client_dev.py -O readgroupsets-get dataset1:remote http://localhost:8000/currentdataset1:remote
```
Issue #524

Implement  GET /readgroupsets/{id}

---

ga4gh/backend.py
ga4gh/cli.py
ga4gh/client.py
ga4gh/frontend.py
tests/unit/test_cli.py
tests/unit/test_client.py
tests/unit/test_views.py

No tests yet.
```
$ python client_dev.py -O readgroups-get dataset1:remote:wgEncodeUwRepliSeqBg02esG1bAlnRep1_sample http://localhost:8000/current
dataset1:remote:wgEncodeUwRepliSeqBg02esG1bAlnRep1_sample
```
Issue #525

Implement GET /readgroups/{id}

---

ga4gh/backend.py
ga4gh/datamodel/__init__.py
ga4gh/datamodel/datasets.py
ga4gh/datamodel/reads.py
ga4gh/datamodel/references.py
ga4gh/datamodel/variants.py
tests/datadriven/__init__.py
tests/datadriven/test_reads.py
tests/datadriven/test_references.py
tests/datadriven/test_variants.py
tests/end_to_end/test_gestalt.py
tests/unit/test_backends.py
tests/unit/test_compound_ids.py
tests/unit/test_faultydata.py
tests/unit/test_response_generators.py
tests/unit/test_simulated_stack.py
tests/unit/test_simulator.py
tests/unit/test_views.py

This is a fairly widespread refactoring of the datamodel code. Changes:
1. All of the datamodel objects actually inherit from datamodel.DatamodelObject now. Each one has a CompoundId and a localId. 
2. Refactored the CompoundId concept a bit to fit into this.
The aim of this is to get a proper, linked up model in memory of our data tree. This should make issues like #535 simple to fix (should be fixed already, in fact; it would be better to verify this and add some test cases in a follow up PR though).
There's still some tests to fix, but I ran out of time. Hopefully I'll finish this PR later.
Comments/feedback?

Id cleanup

---

.gitignore

The PyCharm/IntelliJ IDEA IDE creates *.iml files to describe projects in the same way it uses the .idea directory, which is already listed in the .gitignore.

Keep PyCharm/IntelliJ module files out of the repo.

---

.whiskey/action_hooks/pre-build

It might make sense to maintain a fork of the mod_wsgi image if we need more changes like this, but this builds nicely.  I would prefer to deprecate the ubuntu/centos images. Resolves #484 and #505. https://hub.docker.com/r/afirth/ga4gh_server_apache/builds/bmgjxowqrgrsjqugf4ncuen/

install libxslt1-dev and libffi-dev for docker

---

ga4gh/backend.py
ga4gh/cli.py
ga4gh/datamodel/__init__.py
ga4gh/datamodel/datasets.py
ga4gh/datamodel/references.py
ga4gh/exceptions.py
ga4gh/frontend.py
ga4gh/templates/index.html
tests/end_to_end/test_gestalt.py
tests/unit/test_backends.py
tests/unit/test_compound_ids.py
tests/unit/test_response_generators.py
tests/unit/test_simulated_stack.py

- This changes reference handling to be symmetrical with the way datasets
are managed (fully hierarchical).
- Fixed a missing part of the CLI and API where referenceSets were not
correctly passed to searchReferences.
- Provide getters for all datamodel objects from the backend so that
tests can access the data through a uniform interface.
- Revert a recent change to make the empty string a valid identifier
again (so we correctly 404 when someone provides a non-existant ID as a
parameter, not a different error).
Also, verifies that issues #531 and #535 have been resolved.

Refactor reference handling and some tests.

---

ga4gh/backend.py
ga4gh/datamodel/__init__.py
ga4gh/datamodel/variants.py
ga4gh/exceptions.py
tests/unit/test_compound_ids.py
tests/unit/test_simulated_stack.py

This PR fixes some miscellaneous issues relating to CallSets, and updates the top level object search code so that we always 404 when a missing ID is provided as an argument.
See the commit messages for the issues involved. I've left it as two commits as these deal with different issues.

Search filters

---

ga4gh/backend.py
ga4gh/datamodel/datasets.py
ga4gh/datamodel/reads.py
ga4gh/exceptions.py
ga4gh/frontend.py
tests/end_to_end/test_gestalt.py
tests/unit/test_response_generators.py
tests/unit/test_simulated_stack.py
tests/unit/test_simulator.py
tests/unit/test_views.py

- Refactored to make ID search fully hierarchical
- Added support for searching ReadGroupSets by name (issue #534)
- Generalised the simulator initialisation structures
- Removed multiple locations for initialising internal maps, preferring
the use of addDataset, addVariantSet, etc.
- Fixed up some test cases that depended on brittle interfaces.

Search by name support in readGroupSets + refactor.

---

ga4gh/datamodel/__init__.py
tests/datadriven/test_variants.py
tests/end_to_end/test_gestalt.py
tests/end_to_end/test_oidc.py
tests/end_to_end/test_remote_fetch.py
tests/unit/test_backends.py
tests/unit/test_compound_ids.py
tests/unit/test_views.py

This obfuscates our hierarchical breadcrumb-trail ID format from clients. Clients should not depend on our internal ID values, which are private to a given server instance.  This discourages them from doing so.

ID obfuscation via base64 encoding.

---

ga4gh/frontend.py
tests/end_to_end/client.py
tests/unit/test_protocol_errors.py
tests/unit/test_simulated_stack.py
tests/unit/test_views.py
tests/utils.py

This PR removes the URL based versioning mechanism, and is the first step towards a content-type negotiation schema discussed in #526.
Since URL versioning is not part of the schema, and we are planning on replacing this with a header-based approach, it is a good idea to remove this URL based approach now rather than later. Since this is the reference implementation, other implemetors might assume that URL based API versioning is required.

Removed URL versioning.

---

ga4gh/backend.py
ga4gh/datamodel/datasets.py
ga4gh/datamodel/reads.py
ga4gh/datamodel/variants.py
ga4gh/exceptions.py
tests/unit/test_backends.py

This PR completes the process of refactoring client-facing getter methods to within their actual containers. This is safer than passing around maps, as there is a single location where we must raise the correct exception. This also gives a better interface, as we can change the internal indexing structures without affecting client code.

Complete refactor to explicit getter methods.

---

ga4gh/backend.py
ga4gh/datamodel/datasets.py
ga4gh/datamodel/reads.py
ga4gh/datamodel/references.py
ga4gh/datamodel/variants.py
tests/datadriven/test_variants.py
tests/unit/test_backends.py

This removes the need for passing around references to internal
structures, and allows us to program against an interface rather than an
internal representation.
Depends on PR  #575, which should be reviewed first.

Remove external map access

---

tests/end_to_end/test_remote_fetch.py

Does not resolve #500 ... that's blocked because pysam does not yet have the hooks into the htslib methods we need to write remote index files where we want them to go.

Temporary fix to cleanup htslib-downloaded indexes

---

ga4gh/converters.py
ga4gh/datamodel/reads.py

I am not a Python programmer, and I have not attempted to feed this to a python.  Your mileage may vary.  But I do know what (SAM) plugs into what (GA4GH).  Fixes #491.
(Not too sure why there's this `SamFlags` class rather than using `is_reverse(read)` et al as supplied by pysam…?)

Implement read strand flags

---

scripts/download_data.py

- remove X and Y chroms
- make data conform to new read dir structure
Issue #614
Default run now produces:
```
$ find ga4gh-downloaded-data/
ga4gh-downloaded-data/
ga4gh-downloaded-data//dataset1
ga4gh-downloaded-data//dataset1/reads
ga4gh-downloaded-data//dataset1/reads/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam
ga4gh-downloaded-data//dataset1/reads/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam.bai
ga4gh-downloaded-data//dataset1/reads/HG00533.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522.bam
ga4gh-downloaded-data//dataset1/reads/HG00533.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522.bam.bai
ga4gh-downloaded-data//dataset1/reads/HG00534.mapped.ILLUMINA.bwa.CHS.low_coverage.20120522.bam
ga4gh-downloaded-data//dataset1/reads/HG00534.mapped.ILLUMINA.bwa.CHS.low_cove …
```

Fix download data script

---

ga4gh/backend.py
ga4gh/cli.py
ga4gh/datamodel/references.py
tests/unit/test_cli.py
tests/unit/test_simulated_stack.py

Also brings cli up to date with reference schema changes.
We add filtering to reference and reference sets search in the most straightforward way I could think of. It is disappointing that we have to build a list of all the objects, but this avoids a lot of tricky issues. The number of references and reference sets is likely to be rather small, so I doubt this will be an issue in practice.
The tests aren't entirely exhaustive, but they should exercise the code well enough.
Issues #539 and #540.

Adds reference search filters.

---

Dockerfile
requirements.txt

This updates the graph server's dockerfile to install the dependencies using pip, and adds in the missing pyfasta dependency.

Set Docker to install dependencies, and list all dependencies

---

ga4gh/cli.py
ga4gh/client.py
ga4gh/converters.py
tests/end_to_end/client.py
tests/end_to_end/server_test.py
tests/end_to_end/test_gestalt.py
tests/end_to_end/test_oidc.py
tests/unit/test_cli.py
tests/unit/test_client.py
tests/unit/test_converters.py

This is a WIP, so comments welcome. The PR depends on #641 and #634, so has a pretty large diff right now. This should look more sensible once these are merged and this is rebased.
The basic idea here is to refactor the CLI and client library so that we can make the client application smarter. If we give ``variant-sets-search`` no dataset arguments, we run the search over all datasets. Similar logic applies to all the other requests: if we don't specify enough information, the client application will query the server and do the right thing. We also add JSON output, which I think is quite useful and might persuade people to stop using CURL to query the server. These changes are all motivated by the upcoming documentation updates, which are going to be hard to write with any clarity using …

CLI refactor

---

ga4gh/cli.py
ga4gh/client.py
tests/unit/test_client.py

Having a pageSize argument on all of the  searchX methods in the httpClient is confusing. This is a low-level network utilisation knob, which doesn't affect the output of the methods in any way. It therefore makes much more sense to make this an attribute of the httpClient rather than to pass it in as a parameter to each search call.

Made pageSize an attribute of httpClient.

---

ga4gh/protocol.py

Logically can't happen, as everything must be a ProtocolElement for this encoded to be called.

Removed unused branch in if statement.

---

ga4gh/cli.py
tests/end_to_end/test_client_json.py

This PR adds an experimental file:// prefix for the command line client. This is mainly for testing, as it gives us a nice way to test the CLI against a specific backend without faffing around with sockets. Adds some framework for CLI tests where we check the JSON we output on the command line is what we expect.
Depends on #699, as both edit cli.py.

Client json tests

---

ga4gh/client.py

Incorporate Avro documentation from ga4gh/schemas into ga4gh/client.py docstrings. Closes issue 674.

Fix missing parameter in client API docs

---

tests/end_to_end/server.py

I was poking around for a couple minutes and couldn't find the offending port, or an open terminal. This makes it easier.

Provide a useful error if server appears to already be running during the server end to end test

---

ga4gh/converters.py
ga4gh/datamodel/reads.py
tests/unit/test_converters.py

Make this routine return the value instead.

Routine to set sam flags mistakenly assumes integer is passed by ref

---

tests/unit/test_variants.py

Applies to Issue #690 
Generates some a SimulatedVariantSet for use in testing methods that require a variant see https://github.com/jsh2134/server/commit/341ad1c19ee490c608174c510ce2fba7f4ec8136#diff-7858b4c3a3f24acfcfa6d89486e1544cR167 and https://github.com/jsh2134/server/commit/341ad1c19ee490c608174c510ce2fba7f4ec8136#diff-7858b4c3a3f24acfcfa6d89486e1544cR175

Tests for AbstractVariantSet - Issue #690

---

ga4gh/cli.py
tests/unit/test_cli.py

Make ListReferenceBasesRunner be able to output in FASTA or text depending on the option

Output FASTA for reference-bases-list command

---

.travis.yml

Good news: we're doing pretty good on branch coverage; our test coverage percentage only slips from 93 to 91 with the branch coverage option enabled.
Issue #700

Add branch miss coverage option to nosetests

---

MANIFEST.in
README.pypi.rst
README.txt
setup.py

Here is the counter proposal for #774. I prefer this; the landing pages for PyPI and GitHub can now evolve independently, as we don't have to compromise on the content that is suitable for both.

Split landing pages into dev and stable.

---

CONTRIBUTING.md
ga4gh/frontend.py
ga4gh/serverconfig.py
requirements.txt
tests/end_to_end/server.py
tests/unit/test_oidc.py
tests/unit/test_simulated_stack.py
tests/unit/test_views.py

Instead of `__EMPTY__` we use `empty://`. Instead of `__SIMULATED__` we use things like `simulated://?numCalls=5&numReferencesPerReferenceSet=1` (and pull the un-specified values from the config). Currently-used file paths get automatically turned into `file://` URLs, and `file://` URLs can be accepted.
Unless your config requested `__EMPTY__` or `__SIMULATED__`, this is backwards-compatible. It also potentially will let us do stuff like `mysql://` in the future if we get more different backends. Maybe one for `graphdatabase://`?
I sort of thought this might help with #717, keeping with the theme of improving the simulated backend.

Use URLs to specify data sources

---

oidc-provider/run.sh
oidc-provider/setupenv.sh
oidc-provider/simple_op/requirements.txt
requirements.txt
tests/end_to_end/server.py
tests/end_to_end/test_oidc.py

This should fix the current CI problems of issue #792.
We had an embedded virtualenv to run the simple_op provider, which started to cause trouble on travis's setup. This was always going to cause issues in any case as it meant we couldn't run the tests from a virtualenv (I don't think venv's nest very well).
Let's see if this fixes the problem anyway.

Remove virtualenv for simple_op server.

---

ga4gh/_protocol_definitions.py

Result of running 
```
python scripts/process_schemas.py  v0.6.0a1
```
No differences other than schema version.

Update schemas to v0.6.0a1.

---

setup.py

Uses versions found in requirements.txt. Install currently fails without this because of problems with pysam 0.8.4.

Pinned install versions of packages.

---

docs/api.rst

Add link to GA4GH schema docs in client docs

---

docs/introduction.rst
docs/status.rst

1. Fixed the link for the schema documentation.
2. Updated the release notes to change 0.2.0a1 to 0.2.0, since there
were no changes between these releases.

Miscellaneous documentation fixes.

---

.travis.yml

Using Travis's cache and a recent version of pip we can cache binary packages. Reduces builds from ~7minutes to 1.5 minutes.
Also change the install script to build the source distribution and install from this, allowing us to test the distribution mechanisms.

Use caching to speed up build times

---

ga4gh/__init__.py
setup.py
tests/unit/test_imports.py

Issue #790 
Also a minor refactor of setup.py.
@reece --- it would be great to get your thoughts here. I based this off what you've done in hgvs, but thought the ``"write_to": "ga4gh/_version.py"`` was a bit simpler than ``pkg_resources`` (which I think could potentially be misleading for a developer?).

Use setuptools_scm to set version numbers.

---

README.txt

The usual practise on RTD is to make the ``latest`` version represent the bleeding edge in master. This updates the links in the GitHub readme to update new links.

Fixes read-the-docs link for latest docs.

---

ga4gh/_protocol_definitions.py
ga4gh/backend.py
ga4gh/datamodel/variants.py

Depends on Jerome's #839. Brings Variant annotation in line with the latest schemas and removes features slated for a later release. Namely, removed reference to datasetId when finding a variant annotation set, removed reference to searching by featureId, and removed reference to colocated variants.

Variant annotation new schemas

---

tests/unit/test_simulated_stack.py
tests/unit/test_views.py

Tests for Issue #684 
This adds a few more unit tests to cover cases where a reference is not specified or multiple readGroupIds are sent. In all cases the response is expected to be a 501.

Adds tests for unmapped reads and multiple readGroups - Issue #684

---

ga4gh/datamodel/variants.py

Pulls out HGVSg records from annotated VCFs from the new test data to fix #838

Add genomic coordinates to annotation records

---

ga4gh/backend.py
ga4gh/client.py
ga4gh/datamodel/datasets.py
ga4gh/datamodel/variants.py
ga4gh/datarepo.py
ga4gh/frontend.py
ga4gh/templates/index.html
tests/unit/test_client.py

This PR attempts to formalize the relationship between variant sets and variant annotation sets. Previously, it was possible to have variant annotations for variants that weren't present in GA4GH. Now annotation VCFs are considered a source of a variant set as well as a variant annotation set.
This is done by placing a small description JSON next to the VCF in the directory. For now, this file simply denotes whether the VCF is annotated or not.
{
"isAnnotated": true
}
Furthermore, the requirement of placing the variant object within the annotation has been removed: annotations now maintain the start and end coordinates themselves so they can be searched across without looking up the variant.

Variant annotation with variant sets

---

ga4gh/frontend.py

Fixes a bug from recent changes that would cause server to fail to start.
Traceback (most recent call last):
File "server_dev.py", line 7, in <module>
ga4gh.cli.server_main()
File "/Users/david/ga4gh/server-1/ga4gh/cli.py", line 77, in server_main
args.config_file, args.config, args.port)
File "/Users/david/ga4gh/server-1/ga4gh/frontend.py", line 206, in configure
dataRepository.checkConsistency()
AttributeError: 'FileSystemDataRepository' object has no attribute 'checkConsistency'

Point to function for consistency check

---

requirements.txt
tests/end_to_end/test_client_json.py

I've been working on building out these tests for Issue #704  and had a couple questions:
1. There are cli endpoints for get and search callset, but it looks like these methods haven't been implemented on the local file backend. Are there plans to support this? I added a skipped unit tests for each, but these can be removed if it won't be supported
2. There is currently no cli call for variantsets-get. Again added a skipped unit test. 
3. A few of the api calls take long enough that the system time is different between the interal api call and the call via the cli. This causes issues when comparing "updated" timestamps in the response object. The way I've dealt with this in the past is to use something like [freezegun](https://github.com/spulec/freezegun). I added this as a dependency, …

Issue 704: Adds client json tests

---

scripts/download_data.py
scripts/process_schemas.py
tests/datadriven/test_references.py

These cause failures in the protobuf based server when run against the current example data.
Also fixes some pep8 issues.

Updates data download script to remove nulls.

---

ga4gh/_protocol_definitions.py
ga4gh/datamodel/variants.py
tests/unit/test_simulator.py

Variant annotations currently have a `created` field that uses unix timestamp. To come in line with https://github.com/ga4gh/schemas/pull/552 this PR adds a test to ensure the created time follows ISO8601.

Change created field of variant annotation to ISO8601

---

ga4gh/backend.py
ga4gh/cli.py
ga4gh/client.py
ga4gh/frontend.py
tests/end_to_end/test_client_json.py
tests/unit/test_cli.py
tests/unit/test_client.py
tests/unit/test_views.py

In addition to adding these methods, I went through and standardardize the way callSet was referenced -- in some places it was callset and in others it was callSet. It seems like the apis are usually capitalizing Set, so I went with that convention.

Issue #893: Adds api on local client for getCallset and searchCallset

---

ga4gh/backend.py

Without this, the compliance test causes 400 errors as ultimately ga4gh.datamodel.assertValidRange explodes whenever a pageToken is used because the pageToken sets the start, but the end is left at 0. With this change, the end is forced to None, which avoids the problem.

Ensure treatment of request.end is the same regardless of how the iterator is initialised

---

tests/datadriven/__init__.py

Hidden files have a leading `.` and are picked up by the datadriven test framework. This should handle many cases of picking up unwanted files. fix #913

Ignore hidden files for datadriven tests

---

ga4gh/datamodel/reads.py
tests/unit/test_reads.py

This adds a bunch of tests for `datamodel.reads` for #687 that make sure that the SAM spec is followed and that the utility functions work as expected.
I fixed a couple edge cases in `parseMalformedBamHeader` method and made it robust to correctly parsed headers.

Issue #687: Adds tests for reads

---

ga4gh/datamodel/__init__.py
tests/end_to_end/test_gestalt.py
tests/unit/test_compound_ids.py

Putting `=` in identifiers was a side effect of base64 encoding. This PR attempts to hide them from the user while not functionally changing the identifier scheme. Fix #860

Remove padding from identifiers and add it back in as needed

---

ga4gh/cli.py
ga4gh/datamodel/__init__.py
ga4gh/datamodel/reads.py
ga4gh/datamodel/variants.py
ga4gh/datarepo.py
ga4gh/frontend.py
ga4gh/repo_manager.py
tests/end_to_end/test_repo_manager.py
tests/unit/test_faultydata.py
tests/unit/test_repo_manager.py

So the problem here is that when we are initializing the server data model we also check for consistency in that model and throw errors if it is not consistent.  This is inconvenient for the repo manager since a data repo could very well have been put in an inconsistent state by a user, and we don't want to throw errors in that case.  The previous solution was to sever init and check functionality and to put the later into `checkConsistency` functions which were called on server startup, but not on data repo init.  In this case the 2 functionalities are a bit harder to disentangle.  @jeromekelleher do you think this is the right way to approach this?
Issue #946

WIP InconsistentMetaDataException repomanager bug

---

ga4gh/backend.py
ga4gh/cli.py
ga4gh/client.py
tests/end_to_end/test_gestalt.py
tests/unit/test_client.py
tests/unit/test_simulated_stack.py

Ontology term arrays in the request were not being checked correctly. This PR fixes the variant annotation endpoint to return any ontology terms in the request. A test has been added to ensure order does not affect results. Some refactoring for readability. Fixes https://github.com/ga4gh/server/issues/981

Bug fix for VA search

---

setup.py

Issue #1003.
This may need to be applied to master also, or it might be better to update OIC if it has fixed this issue upstream.
I suggest we follow this up with a quick release of 0.2.1 with just this change to fix this breaking bug.

Pins pyjwkest==1.0.1 to resolve dependency issue.

---

tests/unit/test_exceptions.py

Tests that act on `frontend` must set it to a pristine state before acting. This came up when testing sequence annotations end to end, the exceptions tests were failing because the development config had been activated in another test. This fix simply resets the `frontend`'s state for the test case.
To reproduce create a file `tests/unit/break_exceptions.py`
```
"""
Tests related to exceptions
"""
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
import unittest
import inspect
import ga4gh.exceptions as exceptions
import ga4gh.frontend as frontend
import ga4gh.protocol as protocol
class TestBreakExceptions(unittest.TestCase):
"""
Test that caught exceptions are handled correctly
"""
@classmethod
def setUpClass(cls): …
```

Remove shared state from test_exceptions

---

scripts/prepare_compliance_data.py

This updates the prepare_compliance_data script to download data from the compliance repo. This will improve ease of starting development.
The original default was to add the current directory if no input directory was specified. This changes the default to download from an external source when no input directory is specified, currently `compliance-master`.

Download compliance data from github

---

scripts/prepare_compliance_data.py

Even though it would run successfully, when importing existing data an error would be thrown trying to find the tempdir.
From github:
`python scripts/prepare_compliance_data.py -o ga4gh-example-data`
From compliance test data:
`python scripts/prepare_compliance_data.py -i ~/compliance/test-data -o ga4gh-example-data`

Compliance downloader: properly check for tempdir

---

ga4gh/cli.py
ga4gh/client.py
tests/end_to_end/test_client_json.py
tests/unit/test_cli.py
tests/unit/test_client.py

Client: remove reference to feature ID
Client: Searching by term field alone in the client is handled before sending a request. Closes #1024 
Client: Handle the case when no variant annotation set ID is provided to cli. Closes #1025 
Add tests for variant annotation in test_client_json. Closes #1015

Add test_client_json, remove datasetId reference

---

docs/installation.rst

We've created a new release `data`, that we can add example data as needed. It is possible to add multiple files to a release, so we can manage changes by adding files in the same release, or by creating a new tag.
https://github.com/ga4gh/server/releases/tag/data
Close #998

Update docs to point to new example data

---

deploy/variants/centos-demo-noapache/Dockerfile
deploy/variants/demo/Dockerfile
deploy/variants/ubuntu-demo-apache/Dockerfile
docs/demo.rst
docs/installation.rst
scripts/ga4gh_example.ipynb
scripts/update_data.py

Found a couple of other places where the old example data were being pointed to. Updates the URL to point at a version of the example data with ontologymaps.

Update docs to point at new example data

---

ga4gh/datamodel/__init__.py
tests/datadriven/test_sequenceAnnotations.py
tests/datadriven/test_variants.py
tests/paths.py
tests/unit/test_compound_ids.py
tests/unit/test_views.py

Use json/arrays instead
Issue #1018
Alternate to fix in #1029 (see discussion there)

Refactor CompoundIds to eliminate separators

---

ga4gh/datamodel/references.py

References with dots in their name were crashing the server.

Fixed reference name parsing bug

---

docs/configuration.rst
ga4gh/frontend.py
ga4gh/serverconfig.py
ga4gh/templates/index.html
ga4gh/templates/landing_message.html
tests/end_to_end/test_oidc.py

By setting the `LANDING_MESSAGE_HTML` configuration variable to point at an HTML snippet one can modify the landing page without editing the template directly. A default message has been added in the template directory, `landing_message.html`, which links to the reference server github repo.
I refactored the OIDC test, which was examining strings in HTML tags and was brittle to the inclusion of an HTML comment in the landing page. It now selects the session token tag by class.
Closes #1088

Add landing page snippet

---

docs/installation.rst

Housekeeping for the example data, need to bump the version for the `tar` command. Also, the example data in the data release has been updated so we can close #1091.

Version bump example data

---

ga4gh/frontend.py

While testing deployment @macieksmuga found that the running server wouldn't necessarily be able to reach the directory containing the default landing message. This caused an internal server error.
This PR fixes that case by using flask's render_template to guarantee we are looking at the proper path.

Point at path for landing message in templates dir

---

docs/installation.rst

Minor changes:
* Editing the sites-available and then using apache2ctl to move from sites-available to sites-enabled ([more](http://serverfault.com/questions/83508/purpose-of-debian-sites-available-and-sites-enabled-dirs)). 
* The [apache2ctl](https://httpd.apache.org/docs/current/programs/apachectl.html) tool is a better interface for working with apache than service. Removed the line that used links, this is confusing for many as links is not installed by default. 
* Removed the TODOs, one had been done and the other was too broad to make sense for this document. The general gist, "more example client code," has been captured [elsewhere](https://github.com/ga4gh/server/issues/718).
* Added installation of libcurl headers to apt-get
Aspiring to close #821

Update apache docs

---

ga4gh/cli.py
ga4gh/datamodel/reads.py
ga4gh/datarepo.py
ga4gh/exceptions.py
tests/paths.py
tests/unit/test_cli.py
tests/unit/test_repo_manager.py

This is a PR updating the repo manager. Changes:
1. Changed the SQL schema so that it enforces the integrity of the data model at a schema level using foreign key contraints.
2. Added default name for objects added in the CLI to be derived from the input file.
3. add-readgroupset now supports both local files and remote URLs, along with optionally specifying an index file. The index file is provided via an optional positional argument, so we do ``add-readgroupset repoFile datasetName bam_url index_file``. When a URL is provided, the index is mandatory.
4. Changed the ``check`` command to ``verify``, and reimplemented it. Since the DB schema now guarantees the integrity of the data model, the focus of this command is changed to making sure that the various containers we're pointing at work …

Updates on repo manager

---

ga4gh/cli.py
ga4gh/datamodel/datasets.py
ga4gh/datamodel/ontologies.py
ga4gh/datamodel/sequenceAnnotations.py
ga4gh/datamodel/variants.py
ga4gh/datarepo.py
ga4gh/exceptions.py
tests/datadriven/test_sequenceAnnotations.py
tests/datadriven/test_variant_annotations.py
tests/unit/test_cli.py
tests/unit/test_repo_manager.py
tests/unit/test_variant_annotations.py

Depends on #1104.
Makes two changes:
1. Change the Ontology/OntologyMap object to  OntologyTermMap internally. This is supposed to model what it's doing a bit better. The current setup is rather brittle and will need to be improved, but this at least makes it a bit clearer what's going on (I hope).
2. Ported the CLI support for ontologies to the SQL repo.  The SQL schema and CLI used the term Ontology rather than OntologyTermMap because it seems that the current approach is quite
limited and will need to be changed. This seems more forward compatible, since we don't want to affect uses by making them change CLI syntax or make backwards incompatible changes to the schema.
I would imagine that we would want to update the CLI ``add-ontology`` command to download the map from some …

Ontologies update

---

ga4gh/cli.py
ga4gh/datamodel/datasets.py
ga4gh/datamodel/variants.py
ga4gh/datarepo.py
ga4gh/exceptions.py
tests/unit/test_cli.py
tests/unit/test_repo_manager.py

Depends on #1117 (and #1104 ...). Just look at the last commit for the changes for this PR.
Adds support for variants to the SQL repo and repo manager. The CLI should be quite flexible now, and there's room for it to become more useful. Here's the CLI help:
```
usage: repo_dev.py add-variantset [-h] [-I indexFiles [indexFiles ...]]
[-n NAME] [-R REFERENCESETNAME]
repoPath datasetName dataFiles
[dataFiles ...]
Add a variant set to the data repo based on one or more VCF files.
positional arguments:
repoPath              the file path of the data repository
datasetName           the name of the dataset
dataFiles             The VCF/BCF files representing the new VariantSet.
These may be specified either one or more paths to
local files or remote URLS, or as a path to a local
directory …
```

Sql repo variants

---

docs/configuration.rst
docs/demo.rst
docs/installation.rst

- Removed inaccurate information about file hierarchy
- Updated links to ga4gh-example-data.
We'll want to make a much better job of documenting the repo manager soon (with a nice tutorial on how to set up a repo). This change basically means the information is not inaccurate, although it is quite incomplete.

Updated documentation for SQL repo.

---

ga4gh/datamodel/references.py

This fixes the compliance issue, and ensures that isDerived is the correct type.
Does not fix the underlying problem that this was not detected by the unit tests.

Fix for issue 1164, ensures isDerived is boolean.

---

ga4gh/datamodel/__init__.py
ga4gh/datamodel/variants.py
ga4gh/exceptions.py
tests/datadriven/test_variants.py
tests/unit/test_compound_ids.py
tests/unit/test_references.py
tests/unit/test_sequence_annotations.py
tests/unit/test_variant_annotations.py
tests/unit/test_variants.py

We now require that localIds must be strings
Issue #1187

Handle non-ascii characters in compound ids

---

ga4gh/datamodel/rna_quantification.py

sqlite stores booleans as ints (0 or 1).  This explicitly sets boolean value to True/False rather than relying on python's type conversion which work fine internally but was causing the response JSON to contain the int value instead of a boolean value

explicitly set boolean to True/False

---

ga4gh/datamodel/variants.py
tests/datadriven/test_variants.py
tests/unit/test_variants.py

Most noticeable when the call list is large.
I got at worst a 2x speedup. When an empty callset list is sent you'll see much faster but YMMV.
Replaced the hacked phase set implementation with pysam native. Found that pysam and pyvcf disagree on whether a single genotype in a variant set should be called phased. See demonstration [here](https://gist.github.com/david4096/997fc3ecb00783ba6775acf15750eec4).
Helps with #950

Improvements to the variants API

---

ga4gh/datamodel/references.py

Removes no-op type checks from the ncbiTaxonId code path. The type of the value in the DB is integer, so the value within python must be either an integer or None. Also removes the call to `setNcbiTaxonId` as none of the other attributes did this, and there is no real difference between between ``_ncbiTaxonId`` and the rest.  Calling setters is good practise, but this should be done uniformly within the method on all attributes,  not piecemeal on one.

Removes needless conversion.

---

docs/conf.py
docs/configuration.rst
ga4gh/cli.py
requirements.txt

This is an update to use sphinx-argparse to automatically include documentation about command line arguments. The output isn't ideal, but it's a lot better than trying to maintain two versions of the same documentation.
Here's what it [looks like](http://ga4gh-server-fork.readthedocs.io/en/repo-cli-docs/configuration.html#data-repository) on RTD.
Note that this is not intended as a definitive, final update on these docs. It's just trying out this new technology to see if it's something we want to use to build the final, definitive version of the docs. We're going to need to rephrase a bunch of stuff based on the outcome of #1217.

Added sphinx-argparse based repo manager docs.

---

docs/configuration.rst
ga4gh/datamodel/variants.py
ga4gh/protocol.py
scripts/server_benchmark.py
tests/unit/test_schemas.py
tests/unit/test_simulated_stack.py

Brings server_benchmark up to date, and improves response generation efficiency for protobuf.
Before:
```
jk@holly$ python scripts/server_benchmark.py --profile none WyIxa2ctcDMtc3Vic2V0IiwidnMiLCJtdm5jYWxsIl0
1.929188
```
After:
```
jk@holly$ python scripts/server_benchmark.py --profile none WyIxa2ctcDMtc3Vic2V0IiwidnMiLCJtdm5jYWxsIl0
0.392116
```

Proto perf

---

ga4gh/cli.py
tests/unit/test_repo_manager.py

Forces absolute path when adding a file to the registry. Also test that absolute paths are returned even when relative paths are provided.

Force absolute path when adding close #1204

---

ga4gh/datamodel/variants.py
tests/unit/test_simulated_stack.py

- Adds metadata for simulated VariantSets
- Adds info onto Callset object
It looked like metadata was being added to the VariantSet twice (variants.py:220-222). I removed the later, but I wasn't sure if the intent was exactly the same as in the extend call above. In any case, how it was would fail in testing.
Also, double check if how I'm adding the info dict onto CallSet is how you want to do this. I wasn't really sure what you had in mind, so I just took a stab at it by building out the CallSet class with the field.

Fixes #715

---

ga4gh/backend.py
ga4gh/datamodel/sequenceAnnotations.py
ga4gh/sequence_annotation_service_pb2.py
ga4gh/sequence_annotations_pb2.py
tests/datadriven/test_sequenceAnnotations.py
tests/end_to_end/test_sequenceAnnotations.py

Accompanies https://github.com/ga4gh/schemas/pull/639 and https://github.com/ga4gh/compliance/pull/196
In order to allow for some common access patterns to features data, it has been proposed to allow matching on gene name and gene symbol. This PR demonstrates that functionality within the reference server. 
The handling of requests has been improved for missing values and completed a TODO for generalizing query construction. This does not include a CLI interface, or modifications to the client.

Search features by gene symbol and name

---

ga4gh/client.py
tests/unit/test_client.py

Implements the latest [schema changes](https://github.com/ga4gh/schemas/pull/639) in the client API. Adjusts default values to align with remainder of client API. Adds tests to ensure the fields are set properly.

Add gene symbol and name to features search client

---

ga4gh/cli.py

Issue #1264 
Now looks like:
```
$ python client_dev.py variants-search http://localhost:8000 -s 99718 -e 100000
WyIxa2ctcDMtc3Vic2V0IiwidnMiLCJtdm5jYWxsIiwiMSIsIjk5NzE4IiwiNjhkMTU1ZjQ0Mjg2NzQ4YWI2Njg4ZWQzOTNkZmY2MzQiXQ	WyIxa2ctcDMtc3Vic2V0IiwidnMiLCJtdm5jYWxsIl0	[u'rs183898652']	1	99718	99719	C	[u'T']	EUR_AF=0.00989999994636;SAS_AF=0.00609999988228;AC=0;AA=.|||;AF=0.00898561999202;AFR_AF=0.0143999997526;AMR_AF=0.0143999997526;AN=6;VT=SNP;EAS_AF=0.0;NS=2504;DP=17114;
```

Fix VariantFormatterMixin

---

ga4gh/backend.py
ga4gh/datamodel/variants.py
tests/unit/test_simulated_stack.py

During the protobuf conversion extend was incorrectly used. This bug caused repeated transcript effect records to appear in results. Fixing this bug revealed that the simulated stack tests for VA were incorrect and generated transcript effect records for the same alternate base repeatedly. This PR removes the uncecessary outer loop.
A test has been added to guard for this. Close #1294

Fix VA search bug

---

ga4gh/datamodel/reads.py

Note, I'm not sure what the intended behavior is here. It seems like stats are on both the RG and RGS level, but they derive their data from the same place. This PR simply initializes values checked by `getStats` to `-1`.
Closes https://github.com/ga4gh/server/issues/1304

Add initial counts to read group set

---

ga4gh/datamodel/rna_quantification.py
scripts/prepare_compliance_data.py
scripts/rnaseq2ga.py

In order to make feature IDs in the RNA expression levels point to features within an existing repository three changes were made. The rnaseq2ga script now accepts a repository path.
First, when writing expression levels to the database features are searched within the first feature set in the first dataset found. Features are matched based on name and the resulting feature ID is written to the database.
Second, the signature of the usage of this script in prepare compliance data was changed.
And third, the rna data model needed to be modified to read from the feature ID column. It was reporting the 'id' for both name and featureId.
@saupchurch @dcolligan

Align RNA data with existing repository

---

ga4gh/cli.py
ga4gh/client.py
ga4gh/genotype_phenotype_pb2.py
tests/end_to_end/test_client_json.py
tests/unit/test_cli.py
tests/unit/test_client.py

@dcolligan 
This includes tests for:
tests/unit/test_client.py:TestSearchMethodsCallRunRequest
tests/unit/test_cli.py:TestClientArguments
tests/end_to_end/test_client_json.py:TestClientJson
It does not include any new tests for:
tests/unit/test_data_interface.py:TestInterfacingLayer
tests/unit/test_simulated_stack.py:TestSimulatedStack
Note:  this is paired with PR to schemas - https://github.com/ga4gh/schemas/pull/680

added missing client interfaces  

---

ga4gh/backend.py
ga4gh/client.py
ga4gh/frontend.py
tests/unit/test_client.py
tests/unit/test_simulated_stack.py
tests/unit/test_views.py

In an effort to make the API consistent this PR implements the list reference bases endpoint as a POST request (https://github.com/ga4gh/schemas/pull/647), as opposed to a get request with query parameters. This helps to make the API more consistent by making POST requests used for anything that requires paging.
`GET /reference/abcd123/bases?start=0&end=100&pageToken=3`
becomes 
`POST /reference/abcd123/bases {start: 0, end: 100, pageToken: "3"}`
A couple of bits of code that were noted for removal have been cleared out with this. Namely, as suggested in the TODO, we can pass around request objects without hand editing a parameter dictionary.
- Change tests to use post endpoint
- Simplify testing code path
- Change routes for list ref bases
- Add to client

Reference list bases post request

---

scripts/rnaseq2ga.py

A bug was causing the prepare compliance data script to fail for me. Added a break to avoid unnecessary resetting of the feature.

Fix a bug in loading RNA feature IDs for prepare compliance data

---

docs/configuration.rst
ga4gh/backend.py
ga4gh/cli/repomanager.py
ga4gh/client.py
ga4gh/datamodel/rna_quantification.py
ga4gh/repo/rnaseq2ga.py
ga4gh/rna_quantification_pb2.py
ga4gh/rna_quantification_service_pb2.py
scripts/prepare_compliance_data.py

same changes as ga4gh/server#1418
real author is @david4096
This PR allows RNA quantifications to be tagged and queried by biosample
identifiers. It adds an option to use the CLI to tag quantifications
using BioSample names. The test data has not been updated.
Prepare compliance has been updated to tag the rna quantification with
HG00096's biosample ID.
ga4gh/schemas#705

Add biosampleID to RNA quantification

---

docs/status.rst

I would like to include #1441 and #1443 in this release
Will close #1392 
Alpha pre-release supporting major feature update.
- G2P functionality added to support the following API endpoints:
- POST /phenotypeassociationsets/search
- POST /phenotypes/search
- POST /featurephenotypeassociations/search
- Biometadata tags for RNA quantifications.
- Improvements to the RNA quantification ingestion pipeline.
- Migrated CLI related code to cli module.
- Add demonstration RNA quantification data.
- Minor doc fixes
Known Issues
- When searching using a wildcard, *, an Internal Server Error
occurs. #1379
- When listing many Read Group Sets, responses can be quite slow
causing timeouts. #1316

0.3.4 release notes

---

ga4gh/server/datamodel/genotype_phenotype_featureset.py
ga4gh/server/exceptions.py
tests/end_to_end/test_g2p.py

For a features search, if a search field contains a malformed regular expression, a server error was produced. This fix catches the regular expression error and throws a new exception that returns a "400 BAD REQUEST" with the message "Malformed regular expression"
Close #1379

catches malformed regex and throws a new type of exception

---

ga4gh/server/datarepo.py

The readgroupIds were being iterated into directly when at times there are no read group IDs associated with an RNA quantification.
Close #1472

Patch bug for list printing

---

Dockerfile
README.txt
deploy/001-ga4gh.conf
deploy/config.py
docs/development.rst
docs/installation.rst
scripts/prepare_compliance_data.py

The existing install pattern using `python setup.py install` does not install the server to the `ga4gh` namespace in the same way `pip` does. This PR adjusts the documentation to reflect proper installation practices in the Dockerfile, and updates the Dockerfile to include the compliance dataset by default.
Also removes some orphaned documentation.
If you have docker installed you can test it out with `docker run -d -p 8000:80 david4096/server-1:1500_docs`. This will start a server at [http://localhost:8000](http://localhost:8000) hosting the compliance dataset.
I noted that there is a problem with how the G2P feature sets are being loaded in that the path is included in the localId. This causes compliance to fail on some brittle tests on the features protocol. 
Close #1500

Minor docker updates, fix readthedocs

---

constraints.txt
ga4gh/server/repo/rnaseq2ga.py
tests/datadriven/test_rna_quantification.py
tests/unit/test_oidc.py

I made the expression id an auto increment field and sped up reading the expression data from the file. Closes #1549

speed ups to rna quant ingest

---

.travis.yml
constraints.txt
constraints.txt.default
docs/environment.yml
requirements.txt

Also update outdated deploy password

Change deps for release
